export type OperationalGroup = "operate" | "trading" | "system";
export type OperationalMaturity = "static" | "actionable" | "live" | "charted" | "controlled" | "intelligent";

export interface OperationalPageContract {
  route: string;
  group: OperationalGroup;
  label: string;
  purpose: string;
  maturity: OperationalMaturity;
  liveSources: string[];
  requiredSignals: string[];
  gaps: string[];
  safeActions: string[];
  evidence: string[];
}

export interface OperationalPageAudit {
  route: string;
  group: OperationalGroup;
  label: string;
  score: number;
  maturity: OperationalMaturity;
  status: "ready" | "partial" | "blocked";
  missing: string[];
  nextAction: string;
}

const REQUIRED_SURFACE_SIGNALS = [
  "current_state",
  "freshness",
  "trend",
  "coverage",
  "risk",
  "next_action",
  "evidence",
  "safe_controls",
  "audit_trail",
  "drilldown",
];

export const OPERATIONAL_PAGE_CONTRACTS: OperationalPageContract[] = [
  {
    route: "/operate",
    group: "operate",
    label: "Operate",
    purpose: "Show the daily operator command view across blockers, actions, incidents, approvals, runs, and evidence.",
    maturity: "actionable",
    liveSources: ["/api/operating-runtime/summary", "/api/operating-runtime/evidence", "/api/operating-runtime/audit"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["server-first runtime hydration", "closeout audit flow", "evidence drilldowns"],
    safeActions: [],
    evidence: ["operating-runtime evidence", "operating-runtime audit"],
  },
  {
    route: "/operate/blockers",
    group: "operate",
    label: "Blockers",
    purpose: "Explain gated work, why it exists, and what proof clears it.",
    maturity: "actionable",
    liveSources: ["/api/operating-runtime/evidence", "/api/operating-runtime/audit"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["blocker close/reopen audit", "owner SLA", "evidence backlinks"],
    safeActions: [],
    evidence: ["operating-runtime evidence"],
  },
  {
    route: "/operate/actions",
    group: "operate",
    label: "Actions",
    purpose: "Show routed operator tasks with owner, status, next action, and clearing proof.",
    maturity: "actionable",
    liveSources: ["/api/operating-runtime/workbench", "/api/operating-runtime/evidence"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["action completion API", "action history", "closeout audit flow", "owner SLA"],
    safeActions: ["/api/operating-runtime/workbench"],
    evidence: ["workbench records", "operating-runtime evidence"],
  },
  {
    route: "/operate/incidents",
    group: "operate",
    label: "Incidents",
    purpose: "Show incident readiness, live incident records, rollback paths, and response evidence.",
    maturity: "actionable",
    liveSources: ["/api/operating-runtime/incidents", "/api/head-trader/incidents"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["incident timeline", "acknowledgement action", "resolution action", "closeout audit flow"],
    safeActions: ["/api/operating-runtime/incidents"],
    evidence: ["incident evidence"],
  },
  {
    route: "/operate/approvals",
    group: "operate",
    label: "Approvals",
    purpose: "Show decisions and permission policies that gate risky work.",
    maturity: "actionable",
    liveSources: ["/api/operating-runtime/audit"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["approval inbox persistence", "denial/superseded flows", "decision owner SLA"],
    safeActions: ["/api/operating-runtime/permission-decision"],
    evidence: ["permission audit records"],
  },
  {
    route: "/operate/runs",
    group: "operate",
    label: "Recent Runs",
    purpose: "Show operating loop readiness, last run, next run, output, and failure history.",
    maturity: "actionable",
    liveSources: ["/api/system/workers/summary", "/api/operating-runtime/evidence"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["loop run history", "rerun approval packet", "output artifact links"],
    safeActions: ["/api/system/workers/dry-run"],
    evidence: ["loop evidence", "worker dry-run evidence"],
  },
  {
    route: "/system/warehouse",
    group: "system",
    label: "Data Warehouse",
    purpose: "Show capacity, ingest, freshness, mirror, retention, restore proof, jobs, and safe warehouse actions.",
    maturity: "charted",
    liveSources: [
      "/api/system/warehouse/summary",
      "/api/system/warehouse/sources",
      "/api/system/warehouse/series",
      "/api/system/warehouse/jobs",
    ],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["production collector history", "destructive prune approval flow", "external mirror job execution"],
    safeActions: ["/api/system/warehouse/sync", "/api/system/warehouse/restore-proof", "/api/system/warehouse/prune-dry-run"],
    evidence: ["operating-runtime catalog evidence", "restore proof manifest", "warehouse job records"],
  },
  {
    route: "/system/storage",
    group: "system",
    label: "Storage",
    purpose: "Show disk, object store, artifact retention, cleanup candidates, growth rate, and forecast.",
    maturity: "charted",
    liveSources: ["/api/system/storage/summary", "/api/system/storage/series"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["object-store provider adapter", "destructive cleanup approval flow", "long-term persisted growth history"],
    safeActions: ["/api/system/storage/scan"],
    evidence: ["storage scan evidence", "operating-runtime catalog evidence"],
  },
  {
    route: "/system/freshness",
    group: "system",
    label: "Freshness",
    purpose: "Show source freshness matrix, last successful checks, SLA breach, and stale trend.",
    maturity: "charted",
    liveSources: ["/api/system/freshness/summary", "/api/system/freshness/series", "/api/system/warehouse/sources"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["source-level acknowledgement", "long-term SLO burn rate", "project-owned adapter timestamps"],
    safeActions: ["/api/system/freshness/check"],
    evidence: ["freshness check evidence", "operating-runtime data source evidence"],
  },
  {
    route: "/system/workers",
    group: "system",
    label: "Workers",
    purpose: "Show worker status, last run, next run, duration, logs, failures, and rerun controls.",
    maturity: "charted",
    liveSources: ["/api/system/workers/summary", "/api/system/workers/series", "/api/operating-runtime/evidence"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["scheduler next-run source of truth", "worker logs endpoint", "mutating rerun approval flow"],
    safeActions: ["/api/system/workers/dry-run"],
    evidence: ["worker dry-run evidence", "operating-runtime loop evidence"],
  },
  {
    route: "/system/deployments",
    group: "system",
    label: "Deployments",
    purpose: "Show deployed SHA, release history, health checks, rollback proof, and promotion queue.",
    maturity: "charted",
    liveSources: ["/api/system/deployments/summary", "/api/system/deployments/series", "/api/operating-runtime/evidence"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["current deployed SHA adapter", "rollback proof drawer", "mutating deploy approval executor"],
    safeActions: ["/api/system/deployments/check"],
    evidence: ["deployment evidence", "release train records"],
  },
  {
    route: "/system/credentials",
    group: "system",
    label: "Credentials",
    purpose: "Show presence-only credential posture, missing classes, rotation status, and safe test actions.",
    maturity: "charted",
    liveSources: ["/api/system/credentials/summary", "/api/system/credentials/series", "/api/head-trader/credential-status"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["rotation dates", "provider-specific safe tests", "vault-backed lifecycle actions"],
    safeActions: ["/api/system/credentials/scan"],
    evidence: ["secret presence evidence", "credential status contract"],
  },
  {
    route: "/system/models",
    group: "system",
    label: "Models",
    purpose: "Show configured models, provider health, fallback posture, and routing risk.",
    maturity: "live",
    liveSources: ["/api/model/info", "/api/model/options", "/api/model/auxiliary"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["provider latency trend", "fallback incident history", "cost-aware routing SLO"],
    safeActions: [],
    evidence: ["model routing config"],
  },
  {
    route: "/system/automations",
    group: "system",
    label: "Automations",
    purpose: "Show cron jobs, schedules, last runs, next runs, disabled reasons, and failure alerts.",
    maturity: "live",
    liveSources: ["/api/cron/jobs"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["worker runtime correlation", "automation failure SLO", "evidence artifact links"],
    safeActions: [],
    evidence: ["cron job records"],
  },
  {
    route: "/system/sessions",
    group: "system",
    label: "Sessions",
    purpose: "Show session history, retention, continuity, and second-brain/warehouse linkage.",
    maturity: "live",
    liveSources: ["/api/sessions"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["warehouse retention link", "second-brain promotion status", "session quality score"],
    safeActions: [],
    evidence: ["session database"],
  },
  {
    route: "/system/logs",
    group: "system",
    label: "Logs",
    purpose: "Show log streams, severity, source, and incident/action drillthrough.",
    maturity: "live",
    liveSources: ["/api/logs"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["severity aggregation", "incident backlinking", "log retention SLO"],
    safeActions: [],
    evidence: ["log files"],
  },
  {
    route: "/system/plugins",
    group: "system",
    label: "Plugins",
    purpose: "Show installed plugins, capability gaps, update posture, and permission surface.",
    maturity: "live",
    liveSources: ["/dashboard-plugins/registry"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["plugin capability gap scoring", "permission diff history", "plugin health checks"],
    safeActions: [],
    evidence: ["plugin registry"],
  },
  {
    route: "/system/admin",
    group: "system",
    label: "Admin",
    purpose: "Show admin system controls, configuration health, and safety posture.",
    maturity: "live",
    liveSources: ["/api/system/stats", "/api/status"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["control audit linking", "admin action breaker policy", "production mode banner"],
    safeActions: [],
    evidence: ["system stats", "status endpoint"],
  },
  {
    route: "/system/analytics",
    group: "system",
    label: "Analytics",
    purpose: "Show operational analytics across usage, models, workers, warehouse, and dashboard health.",
    maturity: "live",
    liveSources: ["/api/analytics/usage", "/api/analytics/models"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["warehouse correlation", "worker correlation", "business impact overlays"],
    safeActions: [],
    evidence: ["analytics database"],
  },
  {
    route: "/second-brain",
    group: "operate",
    label: "Second Brain",
    purpose: "Show Obsidian/Hermes Brain knowledge state, candidates, warehouse sync, and restore proof.",
    maturity: "live",
    liveSources: ["/api/second-brain/summary", "/api/second-brain/candidates", "/api/second-brain/search"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["warehouse sync trend", "knowledge coverage drilldown", "business-unit impact labels"],
    safeActions: ["/api/second-brain/warehouse/sync", "/api/second-brain/staleness/scan"],
    evidence: ["Hermes Brain report", "warehouse restore proof"],
  },
  {
    route: "/compounding-intelligence",
    group: "operate",
    label: "Compounding Intelligence",
    purpose: "Show ten-phase readiness, retrieval readiness, warehouse sync, and memory actions.",
    maturity: "live",
    liveSources: ["/api/second-brain/compounding-intelligence", "/api/second-brain/retrieval-pack"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["scheduled freshness proof", "source-route backlinks", "memory action closeout"],
    safeActions: [],
    evidence: ["compounding intelligence report"],
  },
  {
    route: "/decision-lineage",
    group: "operate",
    label: "Decision Lineage",
    purpose: "Show why major decisions were believed, what changed, and the source-event to memory to decision to outcome trail.",
    maturity: "live",
    liveSources: ["/api/second-brain/decisions"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["resolution actions", "source event backlinks", "outcome measurement trend"],
    safeActions: [],
    evidence: ["Hermes Brain decision records", "decision lineage report"],
  },
  {
    route: "/contradictions",
    group: "operate",
    label: "Contradictions",
    purpose: "Show conflicting memories, decisions, source states, business-risk ranking, and resolution audit trail.",
    maturity: "live",
    liveSources: ["/api/second-brain/contradictions"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["inline resolution actions", "decision lineage backlinks", "research task drill-through"],
    safeActions: ["/api/second-brain/contradictions/detect"],
    evidence: ["Hermes Brain contradiction records", "resolution audit trail"],
  },
  {
    route: "/research-queue",
    group: "operate",
    label: "Research Queue",
    purpose: "Show stale-memory, contradiction, and decision-critical research tasks with required evidence and candidate output.",
    maturity: "live",
    liveSources: ["/api/second-brain/research-tasks"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["inline run/reject actions", "candidate review drill-through", "research age SLO"],
    safeActions: ["/api/second-brain/research-tasks/generate"],
    evidence: ["Hermes Brain research tasks", "generated candidate refs"],
  },
  {
    route: "/operate/chat-actions",
    group: "operate",
    label: "Chat Actions",
    purpose: "Show operator chat prompts and command intents with permission preview.",
    maturity: "actionable",
    liveSources: ["/api/operating-runtime/evidence", "/api/operating-runtime/audit"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["permission preview", "chat result audit writeback", "intent-to-result closeout"],
    safeActions: ["/api/operating-runtime/evidence"],
    evidence: ["chat action intent evidence", "operating-runtime audit"],
  },
  {
    route: "/trading/strategies",
    group: "trading",
    label: "Strategies",
    purpose: "Show live strategy candidates, evidence, hypothesis state, backtest readiness, and promotion gates.",
    maturity: "charted",
    liveSources: ["/api/trading-research/strategies/summary", "/api/trading-research/strategies/series", "/api/trading-intelligence/command-center"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["strategy evidence ledger", "promotion action audit", "source-authored falsification adapters"],
    safeActions: ["/api/trading-research/strategies/review"],
    evidence: ["trading command center strategies", "strategy review evidence"],
  },
  {
    route: "/trading",
    group: "trading",
    label: "Trading Overview",
    purpose: "Show trading command center, source freshness, capital provenance, risk, and action queue.",
    maturity: "live",
    liveSources: ["/api/trading-intelligence/command-center", "/api/trading-intelligence/controls"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["route-specific drilldowns", "historical charts", "evidence backlinks", "control audit closeout"],
    safeActions: ["/api/trading-intelligence/control"],
    evidence: ["trading command center contract"],
  },
  {
    route: "/trading/khashi",
    group: "trading",
    label: "Khashi",
    purpose: "Show Khashi venue/source status, strategy state, capital semantics, and blockers.",
    maturity: "live",
    liveSources: ["/api/trading-intelligence/command-center"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["Khashi-specific panels", "venue account freshness", "strategy evidence drilldown"],
    safeActions: [],
    evidence: ["trading source rows"],
  },
  {
    route: "/trading/investing",
    group: "trading",
    label: "Investing System",
    purpose: "Show Investing System analysis pipeline, source coverage, financial analysis readiness, and blockers.",
    maturity: "live",
    liveSources: ["/api/trading-intelligence/command-center"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["financial-analysis pipeline status", "filing/source freshness", "analysis coverage drilldown"],
    safeActions: [],
    evidence: ["trading source rows"],
  },
  {
    route: "/trading/backtesting",
    group: "trading",
    label: "Backtesting",
    purpose: "Show backtest runs, datasets, assumptions, fees/slippage, results, failures, and comparisons.",
    maturity: "charted",
    liveSources: ["/api/trading-research/backtesting/summary", "/api/trading-research/backtesting/series", "/api/trading-research/strategies/summary"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["source-native backtest run artifacts", "assumption registry", "comparison chart persistence"],
    safeActions: ["/api/trading-research/backtesting/review"],
    evidence: ["backtest readiness evidence", "strategy review evidence"],
  },
  {
    route: "/trading/shadow-paper",
    group: "trading",
    label: "Shadow / Paper",
    purpose: "Show shadow and paper ledgers, order/event timelines, and performance versus baseline.",
    maturity: "live",
    liveSources: ["/api/trading-intelligence/command-center", "/api/trading-intelligence/events"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["dedicated paper ledger", "baseline comparison", "order/event timeline"],
    safeActions: [],
    evidence: ["trading events"],
  },
  {
    route: "/trading/risk",
    group: "trading",
    label: "Risk & Capital",
    purpose: "Show risk limits, breaches, exposure, capital provenance, and acknowledgement workflow.",
    maturity: "live",
    liveSources: ["/api/head-trader/summary", "/api/trading-intelligence/command-center"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["risk acknowledgement flow", "limit breach history", "capital forecast"],
    safeActions: ["/api/head-trader/risk-check"],
    evidence: ["head trader audit", "trading command center"],
  },
  {
    route: "/trading/head-trader",
    group: "trading",
    label: "Head Trader",
    purpose: "Show head-trader incidents, decisions, action catalog, channels, audit, and credential status.",
    maturity: "controlled",
    liveSources: ["/api/head-trader/summary", "/api/head-trader/incidents", "/api/head-trader/audit"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["action-to-evidence closeout", "decision learning loop", "channel delivery SLO"],
    safeActions: ["/api/head-trader/risk-check", "/api/head-trader/decisions"],
    evidence: ["head trader audit", "incident evidence"],
  },
  {
    route: "/trading/evidence",
    group: "trading",
    label: "Trading Evidence",
    purpose: "Browse trading proof across Khashi, Investing System, Head Trader, risks, strategies, and backtests.",
    maturity: "charted",
    liveSources: ["/api/trading-research/evidence/ledger", "/api/trading-research/evidence/series", "/api/trading-intelligence/events"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["artifact previews", "source-native proof hashes", "decision closeout links"],
    safeActions: ["/api/trading-research/evidence/review"],
    evidence: ["trading evidence ledger", "trading events", "strategy/backtest proof rows"],
  },
  {
    route: "/operate/evidence",
    group: "operate",
    label: "Operate Evidence",
    purpose: "Browse evidence artifacts by blocker, action, incident, run, source, and page.",
    maturity: "charted",
    liveSources: ["/api/operating-runtime/evidence", "/api/operating-runtime/audit"],
    requiredSignals: REQUIRED_SURFACE_SIGNALS,
    gaps: ["artifact previews", "proof hashes", "blocker/action backlinks"],
    safeActions: ["/api/operating-runtime/evidence"],
    evidence: ["operating-runtime evidence", "operating-runtime audit"],
  },
];

export function auditOperationalContract(contract: OperationalPageContract): OperationalPageAudit {
  const missing: string[] = [];
  if (!contract.liveSources.length) missing.push("live data contract");
  if (!contract.evidence.length) missing.push("evidence source");
  if (!contract.safeActions.length && contract.maturity === "controlled") missing.push("safe action contract");
  for (const signal of REQUIRED_SURFACE_SIGNALS) {
    if (!contract.requiredSignals.includes(signal)) missing.push(signal);
  }
  const score = Math.max(0, Math.round(((REQUIRED_SURFACE_SIGNALS.length + 3 - missing.length) / (REQUIRED_SURFACE_SIGNALS.length + 3)) * 100));
  return {
    route: contract.route,
    group: contract.group,
    label: contract.label,
    maturity: contract.maturity,
    score,
    status: score >= 85 ? "ready" : score >= 55 ? "partial" : "blocked",
    missing,
    nextAction: contract.gaps[0] ?? "Maintain evidence and regression tests.",
  };
}

export function auditOperationalPages(group?: OperationalGroup): OperationalPageAudit[] {
  return OPERATIONAL_PAGE_CONTRACTS
    .filter((contract) => !group || contract.group === group)
    .map(auditOperationalContract)
    .sort((left, right) => left.score - right.score || left.route.localeCompare(right.route));
}

export function contractForRoute(route: string): OperationalPageContract | undefined {
  return OPERATIONAL_PAGE_CONTRACTS.find((contract) => contract.route === route);
}
