// Generated by scripts/generate-dashboard-operational-maturity-packets.mjs.
// The full operational maturity packet ledger is shipped as a runtime asset so generated dashboard routes do not embed it in the main page chunk.
const dashboardOperationalMaturityPacketsUrl = new URL("./dashboard-operational-maturity-packets.runtime.json", import.meta.url).href;

export interface DashboardOperationalMaturityLayer {
  id: string;
  order: number;
  label: string;
  objective: string;
  status: string;
  buildWork: string[];
  components: string[];
  dataRequirements: string[];
  drilldowns: string[];
  actions: string[];
  acceptance: string[];
  testProof: string[];
  evidence: string[];
}

export interface DashboardOperationalMaturityPacket {
  exportName: string;
  route: string;
  title: string;
  family: string;
  priority: string;
  domain: { label: string; contractName: string; dataRequirements: string[]; drilldowns: string[]; actions: string[] };
  routeStatus: string;
  operationalStage: string;
  score: number;
  primaryQuestion: string;
  operatorDecisions: string[];
  criticalFailureStates: string[];
  sharedComponents: string[];
  dataContracts: string[];
  rollupSignals: string[];
  totals: { layerCount: number; readyLayerCount: number; evidenceLayerCount: number; buildWorkCount: number; acceptanceCount: number; testProofCount: number };
  layers: DashboardOperationalMaturityLayer[];
}

export interface DashboardOperationalMaturityPacketsReport {
  schemaVersion: number;
  generatedAt: string;
  source: string;
  policy: Record<string, unknown>;
  layers: Array<{ id: string; order: number; label: string; objective: string; acceptance: string[]; testProof: string[] }>;
  totals: Record<string, number>;
  packets: DashboardOperationalMaturityPacket[];
}

let dashboardOperationalMaturityPacketsPromise: Promise<DashboardOperationalMaturityPacketsReport> | null = null;

export function loadDashboardOperationalMaturityPackets() {
  dashboardOperationalMaturityPacketsPromise ??= fetch(dashboardOperationalMaturityPacketsUrl).then((response) => {
    if (!response.ok) throw new Error(`Unable to load dashboard operational maturity packets: ${response.status}`);
    return response.json() as Promise<DashboardOperationalMaturityPacketsReport>;
  });
  return dashboardOperationalMaturityPacketsPromise;
}

export { dashboardOperationalMaturityPacketsUrl };
