// Generated by scripts/generate-dashboard-live-source-gap-ledger.mjs.
// The full live-source gap ledger is shipped as a runtime asset so generated dashboard routes do not embed it in the page chunk.
const dashboardLiveSourceGapLedgerUrl = new URL("./dashboard-live-source-gap-ledger.runtime.json", import.meta.url).href;

export interface DashboardLiveSourceGap {
  kind: string;
  label: string;
  source: string;
  status: string;
  freshness: string;
  severity: string;
  remediation: string;
  owner: string;
  targetState: string;
}

export interface DashboardBlockedMutatingAction {
  action: string;
  permission: string;
  auditEvent: string;
  cooldownSeconds: number;
  duplicateWindowSeconds: number;
  disabledReason: string | null;
  remediation: string;
  targetState: string;
}

export interface DashboardLiveSourceRouteGap {
  exportName: string;
  route: string;
  title: string;
  family: string;
  priority: string;
  projectProfile: { id: string; label: string; project: string };
  sourceGapCount: number;
  blockedMutatingActionCount: number;
  sourceGaps: DashboardLiveSourceGap[];
  blockedMutatingActions: DashboardBlockedMutatingAction[];
  nextActions: string[];
}

export interface DashboardLiveSourceGapLedger {
  schemaVersion: number;
  generatedAt: string;
  source: string;
  purpose: string;
  policy: Record<string, unknown>;
  totals: Record<string, number>;
  rollups: Record<string, unknown>;
  routeGaps: DashboardLiveSourceRouteGap[];
}

let dashboardLiveSourceGapLedgerPromise: Promise<DashboardLiveSourceGapLedger> | null = null;

export function loadDashboardLiveSourceGapLedger() {
  dashboardLiveSourceGapLedgerPromise ??= fetch(dashboardLiveSourceGapLedgerUrl).then((response) => {
    if (!response.ok) throw new Error(`Unable to load dashboard live-source gap ledger: ${response.status}`);
    return response.json() as Promise<DashboardLiveSourceGapLedger>;
  });
  return dashboardLiveSourceGapLedgerPromise;
}

export { dashboardLiveSourceGapLedgerUrl };
