// Generated by scripts/generate-dashboard-executive-daily-operating-view.mjs
export const dashboardExecutiveDailyOperatingView: DashboardExecutiveDailyOperatingView = {
  "schemaVersion": 1,
  "generatedAt": "2026-09-24T20:37:30.455Z",
  "source": "scripts/generate-dashboard-executive-daily-operating-view.mjs",
  "status": "needs-attention",
  "summary": {
    "dashboardCount": 10,
    "attentionCount": 0,
    "fullyOperationalScore": 100,
    "driftStatus": "stable",
    "visualStatus": "visual-gate-passed",
    "liveE2eCurrent": 10,
    "monitoringCurrent": 10,
    "healthFailures": 0,
    "safeToCommit": true,
    "safeToDeploy": true,
    "policyStatus": "inside-policy",
    "trendDirection": "stable",
    "forecastStatus": "low-risk",
    "forecastConfidence": "trend-backed",
    "recoveryStatus": "recovery-attention",
    "dataOpsStatus": "blocked",
    "dataOpsScore": 54,
    "dataOpsBlockedLayers": 7,
    "dataOpsWatchLayers": 3
  },
  "actionPosture": {
    "actionInstances": 748,
    "controlledMutations": 408,
    "approvalRequired": 204,
    "maintenanceWindowOnly": 204,
    "unsafeMutations": 0,
    "unknownActions": 0,
    "commandSafePosture": true
  },
  "maturityLayers": [
    {
      "label": "Operating History",
      "status": "inside-policy",
      "detail": "stable",
      "description": "Keeps policy objectives and rolling run history visible."
    },
    {
      "label": "Predictive Causal Intelligence",
      "status": "low-risk",
      "detail": "trend-backed",
      "description": "Forecasts drift risk and maps symptoms to likely causes."
    },
    {
      "label": "Governed Recovery",
      "status": "recovery-attention",
      "detail": "3 auto-safe",
      "description": "Separates safe recovery from approval, maintenance-window, and blocked actions."
    },
    {
      "label": "Data Operations",
      "status": "blocked",
      "detail": "54/100",
      "description": "Tracks collection freshness, warehouse growth, archive readiness, backups, and external sync."
    }
  ],
  "dataOperations": {
    "status": "blocked",
    "score": 54,
    "generatedAt": "2026-09-24T20:34:37.444Z",
    "blockedLayers": [
      {
        "projectId": "khashi-vc",
        "project": "Khashi VC",
        "id": "collection-freshness",
        "evidence": "microstructure-history is 297 minutes old. orderbook-snapshots is 297 minutes old. enriched-market-snapshots is 297 minutes old."
      },
      {
        "projectId": "khashi-vc",
        "project": "Khashi VC",
        "id": "warehouse-mirror",
        "evidence": "Warehouse root is not mounted: /Volumes/Hermes/market-warehouse"
      },
      {
        "projectId": "khashi-vc",
        "project": "Khashi VC",
        "id": "retention-readiness",
        "evidence": "StoreRecord has 1,054,892 estimated dead rows."
      },
      {
        "projectId": "investing-system",
        "project": "Investing System",
        "id": "ledger-cardinality",
        "evidence": "OANDA ledger has 1,242,421 file(s)."
      },
      {
        "projectId": "investing-system",
        "project": "Investing System",
        "id": "archive-readiness",
        "evidence": "No OANDA archive catalog records found."
      },
      {
        "projectId": "investing-system",
        "project": "Investing System",
        "id": "backup-readiness",
        "evidence": "No Postgres backup files visible to Investing."
      },
      {
        "projectId": "investing-system",
        "project": "Investing System",
        "id": "external-sync",
        "evidence": "External root is not mounted: /Volumes/Hermes"
      }
    ],
    "watchLayers": [
      {
        "projectId": "khashi-vc",
        "project": "Khashi VC",
        "id": "worker-stability",
        "evidence": "deploy-khashi-scheduler-1, deploy-khashi-poll-worker-1, deploy-khashi-stream-worker-1, deploy-amari-recorder-1"
      },
      {
        "projectId": "khashi-vc",
        "project": "Khashi VC",
        "id": "freshness-query-readiness",
        "evidence": "StoreRecord has storeName/updatedAt indexing, but needs rollups for cheap last-hour and last-day dashboards."
      },
      {
        "projectId": "khashi-vc",
        "project": "Khashi VC",
        "id": "alert-attribution",
        "evidence": "Alerts can now distinguish disk, Docker cache, Postgres, collection, workers, and mirror status."
      }
    ],
    "projects": [
      {
        "id": "khashi-vc",
        "label": "Khashi VC",
        "status": "blocked",
        "score": 62,
        "checkedAt": "2026-09-24T20:33:09.214Z"
      },
      {
        "id": "investing-system",
        "label": "Investing System",
        "status": "blocked",
        "score": 46,
        "checkedAt": "2026-09-24T20:34:27.749Z"
      }
    ],
    "nextActions": [
      "Mount and verify the warehouse mirror target at /Volumes/Hermes/market-warehouse.",
      "Investigate stale key collection stores and worker write cadence.",
      "Add hourly/daily StoreRecord rollups so freshness and growth dashboards avoid table-wide scans.",
      "Keep destructive retention disabled until mirror proof, rollback proof, and pruning approval gates are present.",
      "Archive and compact the OANDA ledger; file cardinality is now an operational risk.",
      "Create and verify an OANDA archive catalog before the next external sync.",
      "Expose fresh Postgres backups to Investing at the standard backup path after approving the mount/data-access boundary.",
      "Mount the external storage root at /Volumes/Hermes before running write-mode sync.",
      "Wire this maturity report into Nous Hermes and resource-governance Discord attribution."
    ]
  },
  "topPriorities": [
    "Resolve governed recovery audit failures before enabling new action classes.",
    "Resolve 7 blocked data operations layer(s) across Khashi VC and Investing System."
  ],
  "dashboards": [
    {
      "projectId": "tlc-capital-group-os",
      "dashboardId": "tlc-capital-group-os.main",
      "label": "TLC Capital Group OS",
      "status": "operational",
      "route": "https://tlc.tlccapitalgroup.com/dashboard",
      "proofUrl": "https://tlc.tlccapitalgroup.com/dashboard/proof",
      "healthUrl": "https://tlc.tlccapitalgroup.com/health",
      "snapshotUrl": "https://tlc.tlccapitalgroup.com/dashboard-snapshot",
      "latestE2eAt": "2026-09-24T16:41:25.101Z",
      "latestMonitoringAt": "2026-09-24T16:41:30.596Z",
      "visualQualityScore": 100,
      "signals": [
        {
          "id": "live-e2e",
          "description": "Live operator flow passed.",
          "status": "passing"
        },
        {
          "id": "monitoring",
          "description": "Monitoring check passed.",
          "status": "passing"
        },
        {
          "id": "health",
          "description": "Health endpoint passed.",
          "status": "passing"
        },
        {
          "id": "visual",
          "description": "Visual proof passed.",
          "status": "passing"
        },
        {
          "id": "certification",
          "description": "Project certification passed.",
          "status": "passing"
        }
      ],
      "nextAction": "Keep live checks, monitoring, health, and visual proof current."
    },
    {
      "projectId": "nous-hermes-agent",
      "dashboardId": "nous-hermes-agent.dashboard",
      "label": "Nous Hermes Agent",
      "status": "operational",
      "route": "https://agent.tlccapitalgroup.com",
      "proofUrl": "https://agent.tlccapitalgroup.com/dashboard/proof",
      "healthUrl": "https://agent.tlccapitalgroup.com/api/status",
      "snapshotUrl": "https://agent.tlccapitalgroup.com/api/dashboard-snapshot",
      "latestE2eAt": "2026-09-24T16:41:25.101Z",
      "latestMonitoringAt": "2026-09-24T16:41:30.596Z",
      "visualQualityScore": 100,
      "signals": [
        {
          "id": "live-e2e",
          "description": "Live operator flow passed.",
          "status": "passing"
        },
        {
          "id": "monitoring",
          "description": "Monitoring check passed.",
          "status": "passing"
        },
        {
          "id": "health",
          "description": "Health endpoint passed.",
          "status": "passing"
        },
        {
          "id": "visual",
          "description": "Visual proof passed.",
          "status": "passing"
        },
        {
          "id": "certification",
          "description": "Project certification passed.",
          "status": "passing"
        }
      ],
      "nextAction": "Keep live checks, monitoring, health, and visual proof current."
    },
    {
      "projectId": "hermes-os",
      "dashboardId": "hermes.workspace",
      "label": "Hermes OS",
      "status": "operational",
      "route": "https://hermes.tlccapitalgroup.com/",
      "proofUrl": "https://hermes.tlccapitalgroup.com/dashboard/proof",
      "healthUrl": "https://hermes.tlccapitalgroup.com/api/dashboard-summary",
      "snapshotUrl": "https://hermes.tlccapitalgroup.com/api/dashboard-summary",
      "latestE2eAt": "2026-09-24T16:41:25.101Z",
      "latestMonitoringAt": "2026-09-24T16:41:30.596Z",
      "visualQualityScore": 100,
      "signals": [
        {
          "id": "live-e2e",
          "description": "Live operator flow passed.",
          "status": "passing"
        },
        {
          "id": "monitoring",
          "description": "Monitoring check passed.",
          "status": "passing"
        },
        {
          "id": "health",
          "description": "Health endpoint passed.",
          "status": "passing"
        },
        {
          "id": "visual",
          "description": "Visual proof passed.",
          "status": "passing"
        },
        {
          "id": "certification",
          "description": "Project certification passed.",
          "status": "passing"
        }
      ],
      "nextAction": "Keep live checks, monitoring, health, and visual proof current."
    },
    {
      "projectId": "media-engine",
      "dashboardId": "media-engine.ops",
      "label": "Media Engine",
      "status": "operational",
      "route": "https://media.tlccapitalgroup.com/dashboard",
      "proofUrl": "https://media.tlccapitalgroup.com/dashboard/proof",
      "healthUrl": "https://media.tlccapitalgroup.com/health",
      "snapshotUrl": "https://media.tlccapitalgroup.com/dashboard-snapshot",
      "latestE2eAt": "2026-09-24T16:41:25.101Z",
      "latestMonitoringAt": "2026-09-24T16:41:30.596Z",
      "visualQualityScore": 100,
      "signals": [
        {
          "id": "live-e2e",
          "description": "Live operator flow passed.",
          "status": "passing"
        },
        {
          "id": "monitoring",
          "description": "Monitoring check passed.",
          "status": "passing"
        },
        {
          "id": "health",
          "description": "Health endpoint passed.",
          "status": "passing"
        },
        {
          "id": "visual",
          "description": "Visual proof passed.",
          "status": "passing"
        },
        {
          "id": "certification",
          "description": "Project certification passed.",
          "status": "passing"
        }
      ],
      "nextAction": "Keep live checks, monitoring, health, and visual proof current."
    },
    {
      "projectId": "media-business-operations",
      "dashboardId": "media-business-operations.main",
      "label": "Media Business Operations",
      "status": "operational",
      "route": "https://media-business-operations.tlccapitalgroup.com/dashboard",
      "proofUrl": "https://media-business-operations.tlccapitalgroup.com/dashboard/proof",
      "healthUrl": "https://media-business-operations.tlccapitalgroup.com/health",
      "snapshotUrl": "https://media-business-operations.tlccapitalgroup.com/api/dashboard-summary",
      "latestE2eAt": "2026-09-24T16:41:25.101Z",
      "latestMonitoringAt": "2026-09-24T16:41:30.596Z",
      "visualQualityScore": 100,
      "signals": [
        {
          "id": "live-e2e",
          "description": "Live operator flow passed.",
          "status": "passing"
        },
        {
          "id": "monitoring",
          "description": "Monitoring check passed.",
          "status": "passing"
        },
        {
          "id": "health",
          "description": "Health endpoint passed.",
          "status": "passing"
        },
        {
          "id": "visual",
          "description": "Visual proof passed.",
          "status": "passing"
        },
        {
          "id": "certification",
          "description": "Project certification passed.",
          "status": "passing"
        }
      ],
      "nextAction": "Keep live checks, monitoring, health, and visual proof current."
    },
    {
      "projectId": "khashi-vc",
      "dashboardId": "khashi-vc.roc",
      "label": "Khashi VC",
      "status": "operational",
      "route": "https://roc.tlccapitalgroup.com/",
      "proofUrl": "https://roc.tlccapitalgroup.com/dashboard/proof?view=live-market-intelligence",
      "healthUrl": "https://roc.tlccapitalgroup.com/readyz",
      "snapshotUrl": "https://roc.tlccapitalgroup.com/api/dashboard-snapshot",
      "latestE2eAt": "2026-09-24T16:41:25.101Z",
      "latestMonitoringAt": "2026-09-24T16:41:30.596Z",
      "visualQualityScore": 100,
      "signals": [
        {
          "id": "live-e2e",
          "description": "Live operator flow passed.",
          "status": "passing"
        },
        {
          "id": "monitoring",
          "description": "Monitoring check passed.",
          "status": "passing"
        },
        {
          "id": "health",
          "description": "Health endpoint passed.",
          "status": "passing"
        },
        {
          "id": "visual",
          "description": "Visual proof passed.",
          "status": "passing"
        },
        {
          "id": "certification",
          "description": "Project certification passed.",
          "status": "passing"
        }
      ],
      "nextAction": "Keep live checks, monitoring, health, and visual proof current."
    },
    {
      "projectId": "business-mapper",
      "dashboardId": "business-mapper.workspace",
      "label": "Business Mapper / Consulting",
      "status": "operational",
      "route": "https://business-mapper.tlccapitalgroup.com/dashboard",
      "proofUrl": "https://business-mapper.tlccapitalgroup.com/dashboard/proof",
      "healthUrl": "https://business-mapper.tlccapitalgroup.com/health",
      "snapshotUrl": "https://business-mapper.tlccapitalgroup.com/api/dashboard-snapshot",
      "latestE2eAt": "2026-09-24T16:41:25.101Z",
      "latestMonitoringAt": "2026-09-24T16:41:30.596Z",
      "visualQualityScore": 100,
      "signals": [
        {
          "id": "live-e2e",
          "description": "Live operator flow passed.",
          "status": "passing"
        },
        {
          "id": "monitoring",
          "description": "Monitoring check passed.",
          "status": "passing"
        },
        {
          "id": "health",
          "description": "Health endpoint passed.",
          "status": "passing"
        },
        {
          "id": "visual",
          "description": "Visual proof passed.",
          "status": "passing"
        },
        {
          "id": "certification",
          "description": "Project certification passed.",
          "status": "passing"
        }
      ],
      "nextAction": "Keep live checks, monitoring, health, and visual proof current."
    },
    {
      "projectId": "meal-assistant",
      "dashboardId": "meal-assistant.main",
      "label": "Meal Assistant",
      "status": "operational",
      "route": "https://meal.tlccapitalgroup.com/",
      "proofUrl": "https://meal.tlccapitalgroup.com/dashboard/proof",
      "healthUrl": "https://meal.tlccapitalgroup.com/health",
      "snapshotUrl": "https://meal.tlccapitalgroup.com/api/dashboard-snapshot",
      "latestE2eAt": "2026-09-24T16:41:25.101Z",
      "latestMonitoringAt": "2026-09-24T16:41:30.596Z",
      "visualQualityScore": 100,
      "signals": [
        {
          "id": "live-e2e",
          "description": "Live operator flow passed.",
          "status": "passing"
        },
        {
          "id": "monitoring",
          "description": "Monitoring check passed.",
          "status": "passing"
        },
        {
          "id": "health",
          "description": "Health endpoint passed.",
          "status": "passing"
        },
        {
          "id": "visual",
          "description": "Visual proof passed.",
          "status": "passing"
        },
        {
          "id": "certification",
          "description": "Project certification passed.",
          "status": "passing"
        }
      ],
      "nextAction": "Keep live checks, monitoring, health, and visual proof current."
    },
    {
      "projectId": "rinseables-os",
      "dashboardId": "rinseables-os.main",
      "label": "Rinseables OS",
      "status": "operational",
      "route": "https://rinseables.tlccapitalgroup.com",
      "proofUrl": "https://rinseables.tlccapitalgroup.com/dashboard/proof",
      "healthUrl": "https://rinseables.tlccapitalgroup.com/health",
      "snapshotUrl": "https://rinseables.tlccapitalgroup.com/api/dashboard-snapshot",
      "latestE2eAt": "2026-09-24T16:41:25.101Z",
      "latestMonitoringAt": "2026-09-24T16:41:30.596Z",
      "visualQualityScore": 100,
      "signals": [
        {
          "id": "live-e2e",
          "description": "Live operator flow passed.",
          "status": "passing"
        },
        {
          "id": "monitoring",
          "description": "Monitoring check passed.",
          "status": "passing"
        },
        {
          "id": "health",
          "description": "Health endpoint passed.",
          "status": "passing"
        },
        {
          "id": "visual",
          "description": "Visual proof passed.",
          "status": "passing"
        },
        {
          "id": "certification",
          "description": "Project certification passed.",
          "status": "passing"
        }
      ],
      "nextAction": "Keep live checks, monitoring, health, and visual proof current."
    },
    {
      "projectId": "investing-system",
      "dashboardId": "investing-system.roc",
      "label": "Investing System",
      "status": "operational",
      "route": "https://investing.tlccapitalgroup.com/roc",
      "proofUrl": "https://investing.tlccapitalgroup.com/dashboard/proof",
      "healthUrl": "https://investing.tlccapitalgroup.com/health",
      "snapshotUrl": "https://investing.tlccapitalgroup.com/api/dashboard-snapshot",
      "latestE2eAt": "2026-09-24T16:41:25.101Z",
      "latestMonitoringAt": "2026-09-24T16:41:30.596Z",
      "visualQualityScore": 100,
      "signals": [
        {
          "id": "live-e2e",
          "description": "Live operator flow passed.",
          "status": "passing"
        },
        {
          "id": "monitoring",
          "description": "Monitoring check passed.",
          "status": "passing"
        },
        {
          "id": "health",
          "description": "Health endpoint passed.",
          "status": "passing"
        },
        {
          "id": "visual",
          "description": "Visual proof passed.",
          "status": "passing"
        },
        {
          "id": "certification",
          "description": "Project certification passed.",
          "status": "passing"
        }
      ],
      "nextAction": "Keep live checks, monitoring, health, and visual proof current."
    }
  ],
  "evidenceLinks": [
    {
      "label": "Fully Operational Certification",
      "path": "docs/fleet/dashboard-fully-operational-certification.json",
      "status": "fully-operational-certified"
    },
    {
      "label": "Maturity Drift Monitor",
      "path": "docs/fleet/dashboard-maturity-drift-monitor.json",
      "status": "stable"
    },
    {
      "label": "Production Visual Gate",
      "path": "docs/design/dashboard-production-visual-gate.json",
      "status": "visual-gate-passed"
    },
    {
      "label": "Live E2E Registry",
      "path": "docs/design/dashboard-live-e2e-registry.json",
      "status": "10 dashboards"
    },
    {
      "label": "Monitoring Registry",
      "path": "docs/design/dashboard-monitoring-registry.json",
      "status": "10 checks"
    },
    {
      "label": "Fleet Ship Check",
      "path": "docs/fleet/fleet-ship-check.json",
      "status": "deploy-ready"
    },
    {
      "label": "Operating History Policy",
      "path": "docs/fleet/dashboard-operating-history-policy.json",
      "status": "inside-policy"
    },
    {
      "label": "Predictive Causal Intelligence",
      "path": "docs/fleet/dashboard-predictive-causal-intelligence.json",
      "status": "low-risk"
    },
    {
      "label": "Governed Recovery Audit",
      "path": "docs/fleet/dashboard-governed-recovery-audit.json",
      "status": "recovery-attention"
    },
    {
      "label": "Data Operations Maturity",
      "path": "/data/data-ops-maturity/latest.json",
      "status": "blocked"
    }
  ]
};

export interface DashboardExecutiveDailyOperatingView {
  schemaVersion: number;
  generatedAt: string;
  source: string;
  status: "clear" | "needs-attention";
  summary: Record<string, string | number | boolean>;
  actionPosture: {
    actionInstances: number;
    controlledMutations: number;
    approvalRequired: number;
    maintenanceWindowOnly: number;
    unsafeMutations: number;
    unknownActions: number;
    commandSafePosture: boolean;
  };
  maturityLayers: Array<{
    label: string;
    status: string;
    detail: string | number;
    description: string;
  }>;
  dataOperations: {
    status: string;
    score: number;
    generatedAt: string | null;
    blockedLayers: Array<Record<string, string | number | boolean | null>>;
    watchLayers: Array<Record<string, string | number | boolean | null>>;
    projects: Array<Record<string, string | number | boolean | null>>;
    nextActions: string[];
  };
  topPriorities: string[];
  dashboards: Array<{
    projectId: string;
    dashboardId: string;
    label: string;
    status: string;
    route: string | null;
    proofUrl: string | null;
    healthUrl: string | null;
    snapshotUrl: string | null;
    latestE2eAt: string | null;
    latestMonitoringAt: string | null;
    visualQualityScore: number | null;
    signals: Array<{ id: string; description: string; status: string }>;
    nextAction: string;
  }>;
  evidenceLinks: Array<{
    label: string;
    path: string;
    status: string;
  }>;
}
