// Generated by scripts/sync-dashboard-maturity-web-data.mjs.
export const dashboardMaturityGeneratedAt = "2026-08-02T01:35:06.136Z";
export const promotionReadiness = {
  "schemaVersion": 1,
  "generatedAt": "2026-08-02T01:30:40.814Z",
  "itemCount": 7,
  "items": [
    {
      "project": "khashi-vc",
      "name": "Kashi VC",
      "currentBand": "T3A",
      "targetBand": "T3C",
      "auditStatus": "needs-review",
      "visualStatus": "covered",
      "externalWorkItems": 2,
      "score": 48,
      "status": "blocked",
      "blockers": {
        "project": [],
        "central": [
          "token-debt"
        ],
        "external": [
          "external-work"
        ]
      },
      "flatBlockers": [
        "external-work",
        "token-debt"
      ]
    },
    {
      "project": "media-engine",
      "name": "Media Engine",
      "currentBand": "T3B",
      "targetBand": "T3C",
      "auditStatus": "needs-review",
      "visualStatus": "covered",
      "externalWorkItems": 1,
      "score": 59,
      "status": "needs-work",
      "blockers": {
        "project": [],
        "central": [
          "token-debt"
        ],
        "external": [
          "external-work"
        ]
      },
      "flatBlockers": [
        "external-work",
        "token-debt"
      ]
    },
    {
      "project": "media-business-os",
      "name": "Media Business OS",
      "currentBand": "T1A",
      "targetBand": "T3C",
      "auditStatus": "needs-review",
      "visualStatus": "unknown",
      "externalWorkItems": 2,
      "score": 17,
      "status": "blocked",
      "blockers": {
        "project": [
          "visual-coverage"
        ],
        "central": [
          "token-debt"
        ],
        "external": [
          "external-work"
        ]
      },
      "flatBlockers": [
        "visual-coverage",
        "external-work",
        "token-debt"
      ]
    },
    {
      "project": "business-mapper",
      "name": "Business Mapper",
      "currentBand": "T1A",
      "targetBand": "T2B",
      "auditStatus": "needs-review",
      "visualStatus": "covered",
      "externalWorkItems": 2,
      "score": 34,
      "status": "blocked",
      "blockers": {
        "project": [],
        "central": [
          "token-debt"
        ],
        "external": [
          "external-work"
        ]
      },
      "flatBlockers": [
        "external-work",
        "token-debt"
      ]
    },
    {
      "project": "meal-assistant",
      "name": "Meal Assistant",
      "currentBand": "T1A",
      "targetBand": "T3C",
      "auditStatus": "needs-review",
      "visualStatus": "needs-evidence",
      "externalWorkItems": 2,
      "score": 17,
      "status": "blocked",
      "blockers": {
        "project": [
          "visual-coverage"
        ],
        "central": [
          "token-debt"
        ],
        "external": [
          "external-work"
        ]
      },
      "flatBlockers": [
        "visual-coverage",
        "external-work",
        "token-debt"
      ]
    },
    {
      "project": "hermes-os",
      "name": "Hermes OS",
      "currentBand": "T0P",
      "targetBand": "T3C",
      "auditStatus": "needs-review",
      "visualStatus": "unknown",
      "externalWorkItems": 2,
      "score": 9,
      "status": "blocked",
      "blockers": {
        "project": [
          "visual-coverage"
        ],
        "central": [
          "token-debt"
        ],
        "external": [
          "external-work"
        ]
      },
      "flatBlockers": [
        "visual-coverage",
        "external-work",
        "token-debt"
      ]
    },
    {
      "project": "tlc-capital-group-os",
      "name": "TLC Capital Group OS",
      "currentBand": "T0P",
      "targetBand": "T3C",
      "auditStatus": "needs-review",
      "visualStatus": "unknown",
      "externalWorkItems": 2,
      "score": 9,
      "status": "blocked",
      "blockers": {
        "project": [
          "visual-coverage"
        ],
        "central": [
          "token-debt"
        ],
        "external": [
          "external-work"
        ]
      },
      "flatBlockers": [
        "visual-coverage",
        "external-work",
        "token-debt"
      ]
    }
  ]
} as const;
export const visualCoverage = {
  "schemaVersion": 1,
  "generatedAt": "2026-08-02T01:21:27.678Z",
  "freshnessSlaDays": 30,
  "dashboardCount": 8,
  "coveredCount": 5,
  "staleCount": 0,
  "items": [
    {
      "dashboardId": "nous-hermes-agent.dashboard",
      "label": "Nous Hermes Agent",
      "url": "http://127.0.0.1:9119/",
      "hasScreenshot": false,
      "screenshot": null,
      "screenshotUpdatedAt": null,
      "screenshotAgeDays": null,
      "screenshotFresh": false,
      "hasProofUrl": false,
      "hasHealthUrl": true,
      "visualQualityStatus": "unscored",
      "visualQualityScore": null,
      "status": "needs-evidence"
    },
    {
      "dashboardId": "khashi-vc.roc",
      "label": "Khashi VC ROC",
      "url": "https://roc.tlccapitalgroup.com/",
      "hasScreenshot": true,
      "screenshot": "docs/design/production-screenshots/khashi-vc.roc.png",
      "screenshotUpdatedAt": "2026-07-30T18:41:24.055Z",
      "screenshotAgeDays": 2,
      "screenshotFresh": true,
      "hasProofUrl": true,
      "hasHealthUrl": true,
      "visualQualityStatus": "needs-review",
      "visualQualityScore": 83,
      "status": "covered"
    },
    {
      "dashboardId": "media-engine.ops",
      "label": "Media Engine Ops",
      "url": "https://media.tlccapitalgroup.com/dashboard",
      "hasScreenshot": true,
      "screenshot": "docs/design/production-screenshots/media-engine.ops.png",
      "screenshotUpdatedAt": "2026-07-30T15:36:35.859Z",
      "screenshotAgeDays": 2,
      "screenshotFresh": true,
      "hasProofUrl": false,
      "hasHealthUrl": true,
      "visualQualityStatus": "pass",
      "visualQualityScore": 100,
      "status": "covered"
    },
    {
      "dashboardId": "media-business-operations.main",
      "label": "Media Business Operations",
      "url": "https://media-business-operations.tlccapitalgroup.com/dashboard",
      "hasScreenshot": true,
      "screenshot": "docs/design/production-screenshots/media-business-operations.main.png",
      "screenshotUpdatedAt": "2026-07-30T15:36:35.759Z",
      "screenshotAgeDays": 2,
      "screenshotFresh": true,
      "hasProofUrl": false,
      "hasHealthUrl": true,
      "visualQualityStatus": "unscored",
      "visualQualityScore": null,
      "status": "covered"
    },
    {
      "dashboardId": "business-mapper.workspace",
      "label": "Business Mapper Workspace",
      "url": "https://business-mapper.tlccapitalgroup.com/dashboard",
      "hasScreenshot": true,
      "screenshot": "docs/design/production-screenshots/business-mapper.workspace.png",
      "screenshotUpdatedAt": "2026-07-30T15:36:35.754Z",
      "screenshotAgeDays": 2,
      "screenshotFresh": true,
      "hasProofUrl": false,
      "hasHealthUrl": true,
      "visualQualityStatus": "unscored",
      "visualQualityScore": null,
      "status": "covered"
    },
    {
      "dashboardId": "meal-assistant.main",
      "label": "Meal Assistant",
      "url": "https://meal.tlccapitalgroup.com/",
      "hasScreenshot": false,
      "screenshot": null,
      "screenshotUpdatedAt": null,
      "screenshotAgeDays": null,
      "screenshotFresh": false,
      "hasProofUrl": false,
      "hasHealthUrl": true,
      "visualQualityStatus": "unscored",
      "visualQualityScore": null,
      "status": "needs-evidence"
    },
    {
      "dashboardId": "investing-system.roc",
      "label": "Investing System ROC",
      "url": "https://investing.tlccapitalgroup.com/roc",
      "hasScreenshot": true,
      "screenshot": "docs/design/production-screenshots/investing-system.roc.png",
      "screenshotUpdatedAt": "2026-07-30T15:36:35.757Z",
      "screenshotAgeDays": 2,
      "screenshotFresh": true,
      "hasProofUrl": true,
      "hasHealthUrl": true,
      "visualQualityStatus": "unscored",
      "visualQualityScore": null,
      "status": "covered"
    },
    {
      "dashboardId": "hermes.workspace",
      "label": "Hermes Workspace",
      "url": "https://hermes.tlccapitalgroup.com/",
      "hasScreenshot": false,
      "screenshot": null,
      "screenshotUpdatedAt": null,
      "screenshotAgeDays": null,
      "screenshotFresh": false,
      "hasProofUrl": false,
      "hasHealthUrl": true,
      "visualQualityStatus": "unscored",
      "visualQualityScore": null,
      "status": "needs-evidence"
    }
  ]
} as const;
export const visualEvidenceTasks = {
  "schemaVersion": 1,
  "generatedAt": "2026-08-02T01:21:27.672Z",
  "warningAgeDays": 21,
  "blockingAgeDays": 30,
  "itemCount": 3,
  "items": [
    {
      "dashboardId": "nous-hermes-agent.dashboard",
      "label": "Nous Hermes Agent",
      "status": "needs-evidence",
      "priority": "P0",
      "action": "Capture production screenshot evidence and rerun visual coverage report.",
      "screenshotAgeDays": null,
      "warningAgeDays": 21,
      "blockingAgeDays": 30
    },
    {
      "dashboardId": "meal-assistant.main",
      "label": "Meal Assistant",
      "status": "needs-evidence",
      "priority": "P0",
      "action": "Capture production screenshot evidence and rerun visual coverage report.",
      "screenshotAgeDays": null,
      "warningAgeDays": 21,
      "blockingAgeDays": 30
    },
    {
      "dashboardId": "hermes.workspace",
      "label": "Hermes Workspace",
      "status": "needs-evidence",
      "priority": "P0",
      "action": "Capture production screenshot evidence and rerun visual coverage report.",
      "screenshotAgeDays": null,
      "warningAgeDays": 21,
      "blockingAgeDays": 30
    }
  ]
} as const;
export const tokenDebtBacklog = {
  "schemaVersion": 1,
  "generatedAt": "2026-08-02T01:35:06.133Z",
  "advisoryIssueCount": 0,
  "itemCount": 0,
  "items": []
} as const;
export const componentEvidenceBacklog = {
  "schemaVersion": 1,
  "generatedAt": "2026-08-02T01:29:07.487Z",
  "source": "docs/design/dashboard-component-maturity-registry.json",
  "itemCount": 0,
  "items": []
} as const;
export const componentCertification = {
  "schemaVersion": 1,
  "generatedAt": "2026-08-02T01:29:07.464Z",
  "itemCount": 7,
  "certifiedCount": 7,
  "items": [
    {
      "component": "DashboardShell",
      "owner": "@hermes/dashboard-kit",
      "maturity": "certified",
      "requiredForTier": "T1A",
      "requiredEvidence": [
        "state-matrix",
        "keyboard-and-focus-proof",
        "mobile-or-compact-proof",
        "dark-and-density-proof",
        "loading-empty-error-proof",
        "documentation-example"
      ],
      "missingEvidence": [],
      "certified": true
    },
    {
      "component": "DashboardHeader",
      "owner": "@hermes/dashboard-kit",
      "maturity": "certified",
      "requiredForTier": "T1A",
      "requiredEvidence": [
        "state-matrix",
        "keyboard-and-focus-proof",
        "mobile-or-compact-proof",
        "dark-and-density-proof",
        "loading-empty-error-proof",
        "documentation-example"
      ],
      "missingEvidence": [],
      "certified": true
    },
    {
      "component": "DataTable",
      "owner": "@hermes/dashboard-kit",
      "maturity": "certified",
      "requiredForTier": "T2A",
      "requiredEvidence": [
        "state-matrix",
        "keyboard-and-focus-proof",
        "mobile-or-compact-proof",
        "dark-and-density-proof",
        "loading-empty-error-proof",
        "documentation-example"
      ],
      "missingEvidence": [],
      "certified": true
    },
    {
      "component": "ChartPanel",
      "owner": "@hermes/dashboard-kit",
      "maturity": "certified",
      "requiredForTier": "T2A",
      "requiredEvidence": [
        "state-matrix",
        "keyboard-and-focus-proof",
        "mobile-or-compact-proof",
        "dark-and-density-proof",
        "loading-empty-error-proof",
        "documentation-example"
      ],
      "missingEvidence": [],
      "certified": true
    },
    {
      "component": "FilterBar",
      "owner": "@hermes/dashboard-kit",
      "maturity": "certified",
      "requiredForTier": "T2A",
      "requiredEvidence": [
        "state-matrix",
        "keyboard-and-focus-proof",
        "mobile-or-compact-proof",
        "dark-and-density-proof",
        "loading-empty-error-proof",
        "documentation-example"
      ],
      "missingEvidence": [],
      "certified": true
    },
    {
      "component": "DetailDrawerShell",
      "owner": "@hermes/dashboard-kit",
      "maturity": "certified",
      "requiredForTier": "T3A",
      "requiredEvidence": [
        "state-matrix",
        "keyboard-and-focus-proof",
        "mobile-or-compact-proof",
        "dark-and-density-proof",
        "loading-empty-error-proof",
        "documentation-example"
      ],
      "missingEvidence": [],
      "certified": true
    },
    {
      "component": "CommandBar",
      "owner": "@hermes/dashboard-kit",
      "maturity": "certified",
      "requiredForTier": "T3A",
      "requiredEvidence": [
        "state-matrix",
        "keyboard-and-focus-proof",
        "mobile-or-compact-proof",
        "dark-and-density-proof",
        "loading-empty-error-proof",
        "documentation-example"
      ],
      "missingEvidence": [],
      "certified": true
    }
  ]
} as const;
