// Generated by scripts/generate-generated-dashboard-route-maturity.mjs.
export const generatedDashboardRouteMaturity = {
  "schemaVersion": 1,
  "generatedAt": "2026-09-23T19:50:34.806Z",
  "source": "web/src/pages/GeneratedDashboardPages.tsx",
  "policy": {
    "placeholderRoutesAllowed": false,
    "requiredLayerCount": 15,
    "productionReadyRequiresAllLayers": true
  },
  "layers": [
    {
      "id": "route-coverage",
      "order": 1,
      "description": "Route resolves to a real dashboard page and has an owner, priority, and route identity."
    },
    {
      "id": "page-contract",
      "order": 2,
      "description": "Page declares purpose, target user, data contracts, required states, validation, and proof expectations."
    },
    {
      "id": "data-binding",
      "order": 3,
      "description": "Page is wired to live API, warehouse, or generated evidence data with source and freshness context."
    },
    {
      "id": "state-coverage",
      "order": 4,
      "description": "Page renders normal, loading, empty, error, stale, degraded, critical, permission-limited, and mobile states."
    },
    {
      "id": "observability",
      "order": 5,
      "description": "Page shows worker, collector, runner, sync, storage, alert, or deployment status where relevant."
    },
    {
      "id": "drill-down",
      "order": 6,
      "description": "Aggregate signals link to project, source, worker, job, table, event, alert, or evidence-level detail."
    },
    {
      "id": "cross-project-standard",
      "order": 7,
      "description": "Infrastructure telemetry uses shared fleet schemas and can be compared across projects."
    },
    {
      "id": "command-control",
      "order": 8,
      "description": "Operational commands are permissioned, audited, confirmed, and tied to rollback or recovery evidence."
    },
    {
      "id": "alerting-escalation",
      "order": 9,
      "description": "Warnings and critical alerts have thresholds, dedupe, ownership, dashboard links, and resolution tracking."
    },
    {
      "id": "warehouse-storage",
      "order": 10,
      "description": "Collection, database growth, external mirror, retention, pruning, backup, restore, and orphan evidence are visible."
    },
    {
      "id": "component-maturity",
      "order": 11,
      "description": "Page uses dashboard-kit or approved domain components with no static placeholder surface."
    },
    {
      "id": "ux-visual-maturity",
      "order": 12,
      "description": "Layout, density, filters, responsive behavior, severity language, and empty states are production-quality."
    },
    {
      "id": "testing-proof",
      "order": 13,
      "description": "Build, route smoke, contract, state, permission, command, screenshot, and production smoke proof exists."
    },
    {
      "id": "governance-ledger",
      "order": 14,
      "description": "Route status, blockers, evidence, and next maturity action are recorded in this ledger."
    },
    {
      "id": "production-readiness",
      "order": 15,
      "description": "Route is data-bound, tested, deployed, observable, actionable, and regression-protected."
    }
  ],
  "totals": {
    "routeCount": 68,
    "registeredContractCount": 62,
    "familyContractCount": 6,
    "p0Count": 12,
    "p1Count": 9,
    "averageScore": 32
  },
  "entries": [
    {
      "exportName": "HermesOsPage",
      "route": "/hermes-os",
      "title": "Hermes OS",
      "family": "Executive",
      "priority": "P3",
      "currentStage": "family-contract",
      "score": 27,
      "hasRouteMetadata": false,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "cross-project-standard",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind portfolio summaries, action queues, and executive drill-throughs.",
      "proofRequired": [
        "portfolio health data",
        "action queue data",
        "drill-through screenshots",
        "production smoke"
      ]
    },
    {
      "exportName": "DesignSystemPage",
      "route": "/design-system",
      "title": "Design System",
      "family": "Design System",
      "priority": "P2",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect adoption registry, visual proof, and exception retirement data.",
      "proofRequired": [
        "adoption report",
        "exception register",
        "visual screenshots",
        "component validation"
      ]
    },
    {
      "exportName": "DesignIntelligenceCommandCenterPage",
      "route": "/design-intelligence",
      "title": "Design Intelligence Command Center",
      "family": "Design System",
      "priority": "P2",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect adoption registry, visual proof, and exception retirement data.",
      "proofRequired": [
        "adoption report",
        "exception register",
        "visual screenshots",
        "component validation"
      ]
    },
    {
      "exportName": "PackageNativeMigrationsPage",
      "route": "/dashboard-migrations",
      "title": "Package Native Migrations",
      "family": "Operations",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire runner health, queue status, incident flow, and remediation actions.",
      "proofRequired": [
        "worker run ledger",
        "queue telemetry",
        "incident evidence",
        "command audit"
      ]
    },
    {
      "exportName": "ExecutiveSummaryPage",
      "route": "/executive-summary",
      "title": "Executive Summary",
      "family": "Executive",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind portfolio summaries, action queues, and executive drill-throughs.",
      "proofRequired": [
        "portfolio health data",
        "action queue data",
        "drill-through screenshots",
        "production smoke"
      ]
    },
    {
      "exportName": "ExecutiveBriefingRoomPage",
      "route": "/executive-briefing",
      "title": "Executive Briefing Room",
      "family": "Executive",
      "priority": "P3",
      "currentStage": "family-contract",
      "score": 27,
      "hasRouteMetadata": false,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "cross-project-standard",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind portfolio summaries, action queues, and executive drill-throughs.",
      "proofRequired": [
        "portfolio health data",
        "action queue data",
        "drill-through screenshots",
        "production smoke"
      ]
    },
    {
      "exportName": "CentralCommandPage",
      "route": "/central-command",
      "title": "Central Command",
      "family": "Executive",
      "priority": "P0",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind portfolio summaries, action queues, and executive drill-throughs.",
      "proofRequired": [
        "portfolio health data",
        "action queue data",
        "drill-through screenshots",
        "production smoke"
      ]
    },
    {
      "exportName": "ThemeSystemPage",
      "route": "/theme-system",
      "title": "Theme System",
      "family": "Design System",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect adoption registry, visual proof, and exception retirement data.",
      "proofRequired": [
        "adoption report",
        "exception register",
        "visual screenshots",
        "component validation"
      ]
    },
    {
      "exportName": "DashboardMarketplacePage",
      "route": "/dashboard-marketplace",
      "title": "Dashboard Marketplace",
      "family": "Design System",
      "priority": "P2",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect adoption registry, visual proof, and exception retirement data.",
      "proofRequired": [
        "adoption report",
        "exception register",
        "visual screenshots",
        "component validation"
      ]
    },
    {
      "exportName": "DashboardPrototypeLabPage",
      "route": "/dashboard-prototypes",
      "title": "Dashboard Prototype Lab",
      "family": "Design System",
      "priority": "P2",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect adoption registry, visual proof, and exception retirement data.",
      "proofRequired": [
        "adoption report",
        "exception register",
        "visual screenshots",
        "component validation"
      ]
    },
    {
      "exportName": "MainHermesAgentDashboardPrototypePage",
      "route": "/hermes-command",
      "title": "Hermes Command",
      "family": "Design System",
      "priority": "P2",
      "currentStage": "family-contract",
      "score": 27,
      "hasRouteMetadata": false,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "cross-project-standard",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect adoption registry, visual proof, and exception retirement data.",
      "proofRequired": [
        "adoption report",
        "exception register",
        "visual screenshots",
        "component validation"
      ]
    },
    {
      "exportName": "LiveSignalsPage",
      "route": "/live-signals",
      "title": "Live Signals",
      "family": "Operations",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire runner health, queue status, incident flow, and remediation actions.",
      "proofRequired": [
        "worker run ledger",
        "queue telemetry",
        "incident evidence",
        "command audit"
      ]
    },
    {
      "exportName": "TaskRoutingPage",
      "route": "/task-routing",
      "title": "Task Routing",
      "family": "Agents",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind task routing, loop runs, model routing, approvals, and autonomy gates.",
      "proofRequired": [
        "routing ledger",
        "loop heartbeats",
        "approval audit",
        "autonomy gate results"
      ]
    },
    {
      "exportName": "DecisionLedgerPage",
      "route": "/decision-ledger",
      "title": "Decision Ledger",
      "family": "Operations",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire runner health, queue status, incident flow, and remediation actions.",
      "proofRequired": [
        "worker run ledger",
        "queue telemetry",
        "incident evidence",
        "command audit"
      ]
    },
    {
      "exportName": "ModelRoutingPage",
      "route": "/model-routing",
      "title": "Model Routing",
      "family": "Agents",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind task routing, loop runs, model routing, approvals, and autonomy gates.",
      "proofRequired": [
        "routing ledger",
        "loop heartbeats",
        "approval audit",
        "autonomy gate results"
      ]
    },
    {
      "exportName": "OperatingLoopsPage",
      "route": "/operating-loops",
      "title": "Operating Loops",
      "family": "Agents",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind task routing, loop runs, model routing, approvals, and autonomy gates.",
      "proofRequired": [
        "routing ledger",
        "loop heartbeats",
        "approval audit",
        "autonomy gate results"
      ]
    },
    {
      "exportName": "PermissionSecurityPage",
      "route": "/permission-security",
      "title": "Permission Security",
      "family": "Security",
      "priority": "P1",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect permission gates, secret scans, blocked commands, and remediation evidence.",
      "proofRequired": [
        "permission coverage",
        "secret scan results",
        "blocked-command ledger",
        "remediation proof"
      ]
    },
    {
      "exportName": "BusinessOSPage",
      "route": "/business-os",
      "title": "Business OS",
      "family": "Executive",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind portfolio summaries, action queues, and executive drill-throughs.",
      "proofRequired": [
        "portfolio health data",
        "action queue data",
        "drill-through screenshots",
        "production smoke"
      ]
    },
    {
      "exportName": "ProjectSnapshotsPage",
      "route": "/project-snapshots",
      "title": "Project Snapshots",
      "family": "Operations",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire runner health, queue status, incident flow, and remediation actions.",
      "proofRequired": [
        "worker run ledger",
        "queue telemetry",
        "incident evidence",
        "command audit"
      ]
    },
    {
      "exportName": "DurableMemoryPage",
      "route": "/durable-memory",
      "title": "Durable Memory",
      "family": "Data",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire source freshness, warehouse growth, external mirror lag, retention, pruning, and restore proof.",
      "proofRequired": [
        "freshness ledger",
        "storage growth ledger",
        "mirror verification",
        "retention and pruning evidence"
      ]
    },
    {
      "exportName": "PermissionRuntimePage",
      "route": "/permission-runtime",
      "title": "Permission Runtime",
      "family": "Security",
      "priority": "P1",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect permission gates, secret scans, blocked commands, and remediation evidence.",
      "proofRequired": [
        "permission coverage",
        "secret scan results",
        "blocked-command ledger",
        "remediation proof"
      ]
    },
    {
      "exportName": "CostGovernorPage",
      "route": "/cost-governor",
      "title": "Cost Governor",
      "family": "Finance",
      "priority": "P1",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind cost attribution, billing provider data, reconciliation status, and anomaly review.",
      "proofRequired": [
        "provider billing import",
        "attribution ledger",
        "reconciliation proof",
        "anomaly review"
      ]
    },
    {
      "exportName": "LoopRunnerPage",
      "route": "/loop-runner",
      "title": "Loop Runner",
      "family": "Agents",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind task routing, loop runs, model routing, approvals, and autonomy gates.",
      "proofRequired": [
        "routing ledger",
        "loop heartbeats",
        "approval audit",
        "autonomy gate results"
      ]
    },
    {
      "exportName": "BusinessCommandPage",
      "route": "/business-command",
      "title": "Business Command",
      "family": "Operations",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire runner health, queue status, incident flow, and remediation actions.",
      "proofRequired": [
        "worker run ledger",
        "queue telemetry",
        "incident evidence",
        "command audit"
      ]
    },
    {
      "exportName": "AgentWorkbenchPage",
      "route": "/agent-workbench",
      "title": "Agent Workbench",
      "family": "Agents",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind task routing, loop runs, model routing, approvals, and autonomy gates.",
      "proofRequired": [
        "routing ledger",
        "loop heartbeats",
        "approval audit",
        "autonomy gate results"
      ]
    },
    {
      "exportName": "EvaluationGatesPage",
      "route": "/evaluation-gates",
      "title": "Evaluation Gates",
      "family": "Security",
      "priority": "P2",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect permission gates, secret scans, blocked commands, and remediation evidence.",
      "proofRequired": [
        "permission coverage",
        "secret scan results",
        "blocked-command ledger",
        "remediation proof"
      ]
    },
    {
      "exportName": "AutonomyReadinessPage",
      "route": "/autonomy-readiness",
      "title": "Autonomy Readiness",
      "family": "Agents",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind task routing, loop runs, model routing, approvals, and autonomy gates.",
      "proofRequired": [
        "routing ledger",
        "loop heartbeats",
        "approval audit",
        "autonomy gate results"
      ]
    },
    {
      "exportName": "ProjectRegistryPage",
      "route": "/project-registry",
      "title": "Project Registry",
      "family": "Operations",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire runner health, queue status, incident flow, and remediation actions.",
      "proofRequired": [
        "worker run ledger",
        "queue telemetry",
        "incident evidence",
        "command audit"
      ]
    },
    {
      "exportName": "ProjectPlanCommandCenterPage",
      "route": "/project-plan-command",
      "title": "Project Plan Command Center",
      "family": "Operations",
      "priority": "P3",
      "currentStage": "family-contract",
      "score": 27,
      "hasRouteMetadata": false,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "cross-project-standard",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire runner health, queue status, incident flow, and remediation actions.",
      "proofRequired": [
        "worker run ledger",
        "queue telemetry",
        "incident evidence",
        "command audit"
      ]
    },
    {
      "exportName": "TelemetryFabricPage",
      "route": "/telemetry-fabric",
      "title": "Telemetry Fabric",
      "family": "Data",
      "priority": "P1",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire source freshness, warehouse growth, external mirror lag, retention, pruning, and restore proof.",
      "proofRequired": [
        "freshness ledger",
        "storage growth ledger",
        "mirror verification",
        "retention and pruning evidence"
      ]
    },
    {
      "exportName": "IncidentCommandPage",
      "route": "/incident-command",
      "title": "Incident Command",
      "family": "Operations",
      "priority": "P0",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire runner health, queue status, incident flow, and remediation actions.",
      "proofRequired": [
        "worker run ledger",
        "queue telemetry",
        "incident evidence",
        "command audit"
      ]
    },
    {
      "exportName": "DeploymentPromotionPage",
      "route": "/deployment-promotion",
      "title": "Deployment Promotion",
      "family": "Deployment",
      "priority": "P1",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect promotion state, environment health, rollback readiness, and release evidence.",
      "proofRequired": [
        "release artifact",
        "smoke test",
        "rollback plan",
        "environment health"
      ]
    },
    {
      "exportName": "SecretsPosturePage",
      "route": "/secrets-posture",
      "title": "Secrets Posture",
      "family": "Security",
      "priority": "P0",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect permission gates, secret scans, blocked commands, and remediation evidence.",
      "proofRequired": [
        "permission coverage",
        "secret scan results",
        "blocked-command ledger",
        "remediation proof"
      ]
    },
    {
      "exportName": "DataSourceCatalogPage",
      "route": "/data-source-catalog",
      "title": "Data Source Catalog",
      "family": "Data",
      "priority": "P1",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire source freshness, warehouse growth, external mirror lag, retention, pruning, and restore proof.",
      "proofRequired": [
        "freshness ledger",
        "storage growth ledger",
        "mirror verification",
        "retention and pruning evidence"
      ]
    },
    {
      "exportName": "FinanceAttributionPage",
      "route": "/finance-attribution",
      "title": "Finance Attribution",
      "family": "Finance",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind cost attribution, billing provider data, reconciliation status, and anomaly review.",
      "proofRequired": [
        "provider billing import",
        "attribution ledger",
        "reconciliation proof",
        "anomaly review"
      ]
    },
    {
      "exportName": "LearningEnginePage",
      "route": "/learning-engine",
      "title": "Learning Engine",
      "family": "Learning",
      "priority": "P2",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire golden evals, model comparisons, outcomes, regressions, and learning feeds.",
      "proofRequired": [
        "eval run output",
        "outcome feed",
        "regression report",
        "model comparison evidence"
      ]
    },
    {
      "exportName": "AgentEvalLabPage",
      "route": "/agent-eval-lab",
      "title": "Agent Eval Lab",
      "family": "Learning",
      "priority": "P2",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire golden evals, model comparisons, outcomes, regressions, and learning feeds.",
      "proofRequired": [
        "eval run output",
        "outcome feed",
        "regression report",
        "model comparison evidence"
      ]
    },
    {
      "exportName": "ExecutiveCockpitPage",
      "route": "/executive-cockpit",
      "title": "Executive Cockpit",
      "family": "Executive",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind portfolio summaries, action queues, and executive drill-throughs.",
      "proofRequired": [
        "portfolio health data",
        "action queue data",
        "drill-through screenshots",
        "production smoke"
      ]
    },
    {
      "exportName": "ProductionVerificationPage",
      "route": "/production-verification",
      "title": "Production Verification",
      "family": "Deployment",
      "priority": "P0",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect promotion state, environment health, rollback readiness, and release evidence.",
      "proofRequired": [
        "release artifact",
        "smoke test",
        "rollback plan",
        "environment health"
      ]
    },
    {
      "exportName": "CommandGateRuntimePage",
      "route": "/command-gate-runtime",
      "title": "Command Gate Runtime",
      "family": "Security",
      "priority": "P3",
      "currentStage": "family-contract",
      "score": 27,
      "hasRouteMetadata": false,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "cross-project-standard",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect permission gates, secret scans, blocked commands, and remediation evidence.",
      "proofRequired": [
        "permission coverage",
        "secret scan results",
        "blocked-command ledger",
        "remediation proof"
      ]
    },
    {
      "exportName": "TelemetryAdapterKitPage",
      "route": "/telemetry-adapter-kit",
      "title": "Telemetry Adapter Kit",
      "family": "Adapters",
      "priority": "P1",
      "currentStage": "family-contract",
      "score": 27,
      "hasRouteMetadata": false,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "cross-project-standard",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind provider health, credentials posture, rollout state, and failure-mode proof.",
      "proofRequired": [
        "provider contract",
        "connectivity check",
        "failure-mode test",
        "rollout evidence"
      ]
    },
    {
      "exportName": "IncidentIngestionPage",
      "route": "/incident-ingestion",
      "title": "Incident Ingestion",
      "family": "Operations",
      "priority": "P0",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire runner health, queue status, incident flow, and remediation actions.",
      "proofRequired": [
        "worker run ledger",
        "queue telemetry",
        "incident evidence",
        "command audit"
      ]
    },
    {
      "exportName": "PromotionRunnerPage",
      "route": "/promotion-runner",
      "title": "Promotion Runner",
      "family": "Deployment",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect promotion state, environment health, rollback readiness, and release evidence.",
      "proofRequired": [
        "release artifact",
        "smoke test",
        "rollback plan",
        "environment health"
      ]
    },
    {
      "exportName": "SecretScannerPage",
      "route": "/secret-scanner",
      "title": "Secret Scanner",
      "family": "Security",
      "priority": "P0",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect permission gates, secret scans, blocked commands, and remediation evidence.",
      "proofRequired": [
        "permission coverage",
        "secret scan results",
        "blocked-command ledger",
        "remediation proof"
      ]
    },
    {
      "exportName": "CostAttributionEnginePage",
      "route": "/cost-attribution-engine",
      "title": "Cost Attribution Engine",
      "family": "Finance",
      "priority": "P1",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind cost attribution, billing provider data, reconciliation status, and anomaly review.",
      "proofRequired": [
        "provider billing import",
        "attribution ledger",
        "reconciliation proof",
        "anomaly review"
      ]
    },
    {
      "exportName": "LearningIngestionPage",
      "route": "/learning-ingestion",
      "title": "Learning Ingestion",
      "family": "Learning",
      "priority": "P2",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire golden evals, model comparisons, outcomes, regressions, and learning feeds.",
      "proofRequired": [
        "eval run output",
        "outcome feed",
        "regression report",
        "model comparison evidence"
      ]
    },
    {
      "exportName": "ModelEvalHarnessPage",
      "route": "/model-eval-harness",
      "title": "Model Eval Harness",
      "family": "Learning",
      "priority": "P2",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire golden evals, model comparisons, outcomes, regressions, and learning feeds.",
      "proofRequired": [
        "eval run output",
        "outcome feed",
        "regression report",
        "model comparison evidence"
      ]
    },
    {
      "exportName": "CircuitBreakersPage",
      "route": "/circuit-breakers",
      "title": "Circuit Breakers",
      "family": "Security",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect permission gates, secret scans, blocked commands, and remediation evidence.",
      "proofRequired": [
        "permission coverage",
        "secret scan results",
        "blocked-command ledger",
        "remediation proof"
      ]
    },
    {
      "exportName": "ProductionSweepPage",
      "route": "/production-sweep",
      "title": "Production Sweep",
      "family": "Deployment",
      "priority": "P0",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect promotion state, environment health, rollback readiness, and release evidence.",
      "proofRequired": [
        "release artifact",
        "smoke test",
        "rollback plan",
        "environment health"
      ]
    },
    {
      "exportName": "HetznerPromotionExecutionPage",
      "route": "/hetzner-promotion-execution",
      "title": "Hetzner Promotion Execution",
      "family": "Deployment",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect promotion state, environment health, rollback readiness, and release evidence.",
      "proofRequired": [
        "release artifact",
        "smoke test",
        "rollback plan",
        "environment health"
      ]
    },
    {
      "exportName": "CommandGateCoveragePage",
      "route": "/command-gate-coverage",
      "title": "Command Gate Coverage",
      "family": "Security",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect permission gates, secret scans, blocked commands, and remediation evidence.",
      "proofRequired": [
        "permission coverage",
        "secret scan results",
        "blocked-command ledger",
        "remediation proof"
      ]
    },
    {
      "exportName": "ProjectAdapterRolloutPage",
      "route": "/project-adapter-rollout",
      "title": "Project Adapter Rollout",
      "family": "Adapters",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind provider health, credentials posture, rollout state, and failure-mode proof.",
      "proofRequired": [
        "provider contract",
        "connectivity check",
        "failure-mode test",
        "rollout evidence"
      ]
    },
    {
      "exportName": "IncidentAutomationPage",
      "route": "/incident-automation",
      "title": "Incident Automation",
      "family": "Operations",
      "priority": "P0",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire runner health, queue status, incident flow, and remediation actions.",
      "proofRequired": [
        "worker run ledger",
        "queue telemetry",
        "incident evidence",
        "command audit"
      ]
    },
    {
      "exportName": "LiveSecretScanPage",
      "route": "/live-secret-scan",
      "title": "Live Secret Scan",
      "family": "Security",
      "priority": "P0",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect permission gates, secret scans, blocked commands, and remediation evidence.",
      "proofRequired": [
        "permission coverage",
        "secret scan results",
        "blocked-command ledger",
        "remediation proof"
      ]
    },
    {
      "exportName": "CostReconciliationPage",
      "route": "/cost-reconciliation",
      "title": "Cost Reconciliation",
      "family": "Finance",
      "priority": "P1",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind cost attribution, billing provider data, reconciliation status, and anomaly review.",
      "proofRequired": [
        "provider billing import",
        "attribution ledger",
        "reconciliation proof",
        "anomaly review"
      ]
    },
    {
      "exportName": "OutcomeLearningFeedsPage",
      "route": "/outcome-learning-feeds",
      "title": "Outcome Learning Feeds",
      "family": "Learning",
      "priority": "P2",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire golden evals, model comparisons, outcomes, regressions, and learning feeds.",
      "proofRequired": [
        "eval run output",
        "outcome feed",
        "regression report",
        "model comparison evidence"
      ]
    },
    {
      "exportName": "GoldenEvalExecutionPage",
      "route": "/golden-eval-execution",
      "title": "Golden Eval Execution",
      "family": "Learning",
      "priority": "P2",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire golden evals, model comparisons, outcomes, regressions, and learning feeds.",
      "proofRequired": [
        "eval run output",
        "outcome feed",
        "regression report",
        "model comparison evidence"
      ]
    },
    {
      "exportName": "HardBreakerEnforcementPage",
      "route": "/hard-breaker-enforcement",
      "title": "Hard Breaker Enforcement",
      "family": "Security",
      "priority": "P0",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect permission gates, secret scans, blocked commands, and remediation evidence.",
      "proofRequired": [
        "permission coverage",
        "secret scan results",
        "blocked-command ledger",
        "remediation proof"
      ]
    },
    {
      "exportName": "NetworkRunnerAdapterPage",
      "route": "/network-runner-adapter",
      "title": "Network Runner Adapter",
      "family": "Adapters",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind provider health, credentials posture, rollout state, and failure-mode proof.",
      "proofRequired": [
        "provider contract",
        "connectivity check",
        "failure-mode test",
        "rollout evidence"
      ]
    },
    {
      "exportName": "HetznerSshAdapterPage",
      "route": "/hetzner-ssh-adapter",
      "title": "Hetzner SSH Adapter",
      "family": "Adapters",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind provider health, credentials posture, rollout state, and failure-mode proof.",
      "proofRequired": [
        "provider contract",
        "connectivity check",
        "failure-mode test",
        "rollout evidence"
      ]
    },
    {
      "exportName": "SecretProviderAdapterPage",
      "route": "/secret-provider-adapter",
      "title": "Secret Provider Adapter",
      "family": "Security",
      "priority": "P0",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect permission gates, secret scans, blocked commands, and remediation evidence.",
      "proofRequired": [
        "permission coverage",
        "secret scan results",
        "blocked-command ledger",
        "remediation proof"
      ]
    },
    {
      "exportName": "BillingProviderAdapterPage",
      "route": "/billing-provider-adapter",
      "title": "Billing Provider Adapter",
      "family": "Finance",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Bind cost attribution, billing provider data, reconciliation status, and anomaly review.",
      "proofRequired": [
        "provider billing import",
        "attribution ledger",
        "reconciliation proof",
        "anomaly review"
      ]
    },
    {
      "exportName": "ProjectOutcomeEmitterPage",
      "route": "/project-outcome-emitter",
      "title": "Project Outcome Emitter",
      "family": "Learning",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire golden evals, model comparisons, outcomes, regressions, and learning feeds.",
      "proofRequired": [
        "eval run output",
        "outcome feed",
        "regression report",
        "model comparison evidence"
      ]
    },
    {
      "exportName": "ProviderEvalRunnerPage",
      "route": "/provider-eval-runner",
      "title": "Provider Eval Runner",
      "family": "Learning",
      "priority": "P2",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire golden evals, model comparisons, outcomes, regressions, and learning feeds.",
      "proofRequired": [
        "eval run output",
        "outcome feed",
        "regression report",
        "model comparison evidence"
      ]
    },
    {
      "exportName": "BreakerMiddlewarePage",
      "route": "/breaker-middleware",
      "title": "Breaker Middleware",
      "family": "Security",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect permission gates, secret scans, blocked commands, and remediation evidence.",
      "proofRequired": [
        "permission coverage",
        "secret scan results",
        "blocked-command ledger",
        "remediation proof"
      ]
    },
    {
      "exportName": "IncidentSubscriptionPage",
      "route": "/incident-subscriptions",
      "title": "Incident Subscriptions",
      "family": "Data",
      "priority": "P0",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire source freshness, warehouse growth, external mirror lag, retention, pruning, and restore proof.",
      "proofRequired": [
        "freshness ledger",
        "storage growth ledger",
        "mirror verification",
        "retention and pruning evidence"
      ]
    },
    {
      "exportName": "EvidenceArtifactStorePage",
      "route": "/evidence-artifact-store",
      "title": "Evidence Artifact Store",
      "family": "Data",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Wire source freshness, warehouse growth, external mirror lag, retention, pruning, and restore proof.",
      "proofRequired": [
        "freshness ledger",
        "storage growth ledger",
        "mirror verification",
        "retention and pruning evidence"
      ]
    },
    {
      "exportName": "ReleaseTrainOrchestratorPage",
      "route": "/release-train-orchestrator",
      "title": "Release Train Orchestrator",
      "family": "Deployment",
      "priority": "P3",
      "currentStage": "contract-registered",
      "score": 33,
      "hasRouteMetadata": true,
      "completedLayers": [
        "route-coverage",
        "page-contract",
        "component-maturity",
        "governance-ledger",
        "cross-project-standard"
      ],
      "openLayers": [
        "data-binding",
        "state-coverage",
        "observability",
        "drill-down",
        "command-control",
        "alerting-escalation",
        "warehouse-storage",
        "ux-visual-maturity",
        "testing-proof",
        "production-readiness"
      ],
      "nextMaturityAction": "Connect promotion state, environment health, rollback readiness, and release evidence.",
      "proofRequired": [
        "release artifact",
        "smoke test",
        "rollback plan",
        "environment health"
      ]
    }
  ]
} as const;
