// Generated by scripts/generate-generated-dashboard-route-evidence-bindings.mjs.
// The full evidence ledger is shipped as a runtime asset so generated dashboard routes do not embed it in the main page chunk.
const generatedDashboardRouteEvidenceBindingsUrl = new URL("./generated-dashboard-route-evidence-bindings.runtime.json", import.meta.url).href;

export interface GeneratedDashboardRouteEvidenceBinding {
  exportName: string;
  route: string;
  title: string;
  family: string;
  priority: string;
  projectProfile: { id: string; label: string; project: string };
  dataBindingStatus: string;
  observabilityStatus: string;
  drillDownStatus: string;
  freshnessStatus: string;
  freshnessPolicy: { slaDays: number; generatedAt: string; status: string; staleReasonCount: number };
  staleReasons: string[];
  freshnessSummary: { status: string; freshnessStatus: string; currentCount: number; staleCount: number; missingCount: number; severity: string; visibleFields: string[]; lastGeneratedAt: string; nextRefreshAction: string };
  operationalCategories: Array<{ id: string; label: string; status: string; evidence: string }>;
  operationalStatus: string;
  stateCoverage: { status: string; priority: string; family: string; stateFixtures: string[]; evidence: string[]; unprovenStates: string[]; nextStateAction: string };
  uxVisualMaturity: { status: string; priority: string; family: string; density: string; reviewChecklist: string[]; visualEvidence: string[]; nextVisualAction: string };
  infrastructureConnections: { status: string; projectId: string; project: string; operationalCategoryCount: number; connections: Array<{ kind: string; label: string; target: string; evidence: string; status: string }>; aggregateViews: string[]; nextConnectionAction: string };
  payloadMaturity: { status: string; route: string; strategy: string; mainBundlePolicy: string; lazyLoadTrigger: string; guardEvidence: string[]; nextPayloadAction: string };
  nextOperationalAction: string;
  sourceBindings: Array<{ kind: string; label: string; source: string; status: string; freshness: string; matchedId: string | null; detail: string }>;
  dataSignals: string[];
  drillDownTargets: Array<{ label: string; target: string; source: string }>;
  remainingBindingWork: string[];
}

export interface GeneratedDashboardRouteEvidenceBindingsReport {
  schemaVersion: number;
  generatedAt: string;
  purpose: string;
  sourceReports: Record<string, string>;
  policy: Record<string, unknown>;
  totals: Record<string, number>;
  rollups: Record<string, Record<string, Record<string, number>>>;
  routeBindings: GeneratedDashboardRouteEvidenceBinding[];
}

let generatedDashboardRouteEvidenceBindingsPromise: Promise<GeneratedDashboardRouteEvidenceBindingsReport> | null = null;

export function loadGeneratedDashboardRouteEvidenceBindings() {
  generatedDashboardRouteEvidenceBindingsPromise ??= fetch(generatedDashboardRouteEvidenceBindingsUrl).then((response) => {
    if (!response.ok) throw new Error(`Unable to load generated dashboard route evidence bindings: ${response.status}`);
    return response.json() as Promise<GeneratedDashboardRouteEvidenceBindingsReport>;
  });
  return generatedDashboardRouteEvidenceBindingsPromise;
}

export { generatedDashboardRouteEvidenceBindingsUrl };
