// Generated by scripts/generate-generated-dashboard-route-maturity.mjs.
// The full maturity ledger is shipped as a runtime asset so generated dashboard routes do not embed it in the main page chunk.
const generatedDashboardRouteMaturityUrl = new URL("./generated-dashboard-route-maturity-ledger.runtime.json", import.meta.url).href;

export interface GeneratedDashboardRouteMaturityEntry {
  exportName: string;
  route: string;
  title: string;
  family: string;
  priority: string;
  currentStage: string;
  score: number;
  hasRouteMetadata: boolean;
  completedLayers: string[];
  openLayers: string[];
  nextOpenLayer: string;
  layerStatus: Array<{ id: string; order: number; description: string; status: string; evidence: string[]; blocker: string | null }>;
  evidenceBinding: {
    dataBindingStatus: string;
    observabilityStatus: string;
    drillDownStatus: string;
    freshnessStatus: string;
    sourceCount: number;
    signalCount: number;
    drillDownCount: number;
    stateCoverageStatus: string;
    stateFixtureCount: number;
    uxVisualStatus: string;
    uxChecklistCount: number;
    freshnessVisibilityStatus: string;
    infrastructureConnectionStatus: string;
    infrastructureConnectionCount: number;
    payloadMaturityStatus: string;
  } | null;
  nextMaturityAction: string;
  proofRequired: string[];
}

export interface GeneratedDashboardRouteMaturityReport {
  schemaVersion: number;
  generatedAt: string;
  source: string;
  policy: Record<string, unknown>;
  layers: Array<{ id: string; order: number; description: string }>;
  totals: Record<string, number>;
  entries: GeneratedDashboardRouteMaturityEntry[];
}

let generatedDashboardRouteMaturityPromise: Promise<GeneratedDashboardRouteMaturityReport> | null = null;

export function loadGeneratedDashboardRouteMaturity() {
  generatedDashboardRouteMaturityPromise ??= fetch(generatedDashboardRouteMaturityUrl).then((response) => {
    if (!response.ok) throw new Error(`Unable to load generated dashboard route maturity ledger: ${response.status}`);
    return response.json() as Promise<GeneratedDashboardRouteMaturityReport>;
  });
  return generatedDashboardRouteMaturityPromise;
}

export { generatedDashboardRouteMaturityUrl };
