// Generated by scripts/sync-dashboard-tier-assessment.mjs from latest-adoption-report.json.
// Do not edit project tier rows manually; rerun npm run dashboard:tier-assessment:sync.

export interface ProjectTierExternalWorkItem {
  ownerProject: string;
  scope: string;
  priority: string;
  action: string;
  reason: string;
}

export interface ProjectTierAssessment {
  project: string;
  name: string;
  auditStatus: "current" | "needs-review" | "stale" | "missing" | "unregistered" | "invalid";
  coarseTier: { current: number | null; target: number | null };
  currentBand: string;
  currentBandLabel: string;
  targetBand: string;
  targetBandLabel: string;
  implementationMode: string;
  warnings: string[];
  errors: string[];
  nextMove: string;
  externalWorkItems: ProjectTierExternalWorkItem[];
}

export interface TierBand {
  band: string;
  tier: 0 | 1 | 2 | 3;
  label: string;
  meaning: string;
}

export const projectTierGeneratedAt = "2026-08-04T02:09:37.873Z";
export const projectTierSourceHash = "1656e2566b423d3fd83988811259a86ba3f2758bafe7678af9b3f578cc81d7c8";

export const tierBands: TierBand[] = [
  {
    "band": "T0P",
    "tier": 0,
    "label": "Planned or governance-only",
    "meaning": "Project is registered for governance/readiness but has no audited operator surface yet."
  },
  {
    "band": "T0L",
    "tier": 0,
    "label": "Raw legacy surface",
    "meaning": "Dashboard exists as a raw report, debug table, prototype, or ungoverned screen."
  },
  {
    "band": "T1A",
    "tier": 1,
    "label": "Adapter-aligned shell",
    "meaning": "Canonical CSS/static adapter is synced, but no surface-level component inventory is enforceable."
  },
  {
    "band": "T1B",
    "tier": 1,
    "label": "Inventoried one-shell report",
    "meaning": "One-shell route and surfaces are inventoried, but the main operator path still reads as a report."
  },
  {
    "band": "T2A",
    "tier": 2,
    "label": "Hybrid shared-component dashboard",
    "meaning": "Primary surface uses shared-kit contracts through a static or hybrid implementation, but is not fully package-native."
  },
  {
    "band": "T2B",
    "tier": 2,
    "label": "Package-native shared-component dashboard",
    "meaning": "Primary surface imports shared components directly and covers required dashboard states, but is not yet a product-grade cockpit."
  },
  {
    "band": "T3A",
    "tier": 3,
    "label": "Cockpit candidate with review gaps",
    "meaning": "Dashboard targets product-grade cockpit behavior but still has Tier 3 visual, shell, chart, proof, or interaction warnings."
  },
  {
    "band": "T3B",
    "tier": 3,
    "label": "Current static/hybrid product cockpit",
    "meaning": "Audited product-grade cockpit is current, but delivery still depends on static or hybrid adapter infrastructure."
  },
  {
    "band": "T3C",
    "tier": 3,
    "label": "Package-native product cockpit",
    "meaning": "Highest maturity: audited Tier 3 cockpit implemented directly with shared package components and complete proof/validation."
  }
];

export const projectTierAssessments: ProjectTierAssessment[] = [
  {
    "project": "khashi-vc",
    "name": "Kashi VC",
    "auditStatus": "current",
    "coarseTier": {
      "current": 3,
      "target": 3
    },
    "currentBand": "T3C",
    "currentBandLabel": "Package-native product cockpit (T3C)",
    "targetBand": "T3C",
    "targetBandLabel": "Package-native product cockpit (T3C)",
    "implementationMode": "package-native",
    "warnings": [],
    "errors": [],
    "nextMove": "Kashi VC Live Command is the current Tier 3 reference surface for live market cockpit behavior, but the highest maturity target remains T3C package-native delivery.",
    "externalWorkItems": []
  },
  {
    "project": "media-engine",
    "name": "Media Engine",
    "auditStatus": "current",
    "coarseTier": {
      "current": 3,
      "target": 3
    },
    "currentBand": "T3C",
    "currentBandLabel": "Package-native product cockpit (T3C)",
    "targetBand": "T3C",
    "targetBandLabel": "Package-native product cockpit (T3C)",
    "implementationMode": "package-native",
    "warnings": [],
    "errors": [],
    "nextMove": "Media Engine production renderer now imports @hermes/dashboard-kit directly, resolves shared CSS from the package export, and renders package metric primitives. Remaining local chart/table/drawer/state primitives are compatibility code pending full component decomposition.",
    "externalWorkItems": []
  },
  {
    "project": "media-business-os",
    "name": "Media Business OS",
    "auditStatus": "current",
    "coarseTier": {
      "current": 3,
      "target": 3
    },
    "currentBand": "T3C",
    "currentBandLabel": "Package-native product cockpit (T3C)",
    "targetBand": "T3C",
    "targetBandLabel": "Package-native product cockpit (T3C)",
    "implementationMode": "package-native",
    "warnings": [],
    "errors": [],
    "nextMove": "Media Business OS shell and client renderer are inventoried. It has adapter-level alignment but still needs package-native shared components for product-grade operating cockpit completion.",
    "externalWorkItems": []
  },
  {
    "project": "business-mapper",
    "name": "Business Mapper",
    "auditStatus": "current",
    "coarseTier": {
      "current": 2,
      "target": 2
    },
    "currentBand": "T2B",
    "currentBandLabel": "Package-native shared-component dashboard (T2B)",
    "targetBand": "T2B",
    "targetBandLabel": "Package-native shared-component dashboard (T2B)",
    "implementationMode": "package-native",
    "warnings": [],
    "errors": [],
    "nextMove": "Business Mapper workspace is inventoried. It should move from static adapter usage to shared component dashboard quality before being considered complete.",
    "externalWorkItems": []
  },
  {
    "project": "meal-assistant",
    "name": "Meal Assistant",
    "auditStatus": "current",
    "coarseTier": {
      "current": 3,
      "target": 3
    },
    "currentBand": "T3C",
    "currentBandLabel": "Package-native product cockpit (T3C)",
    "targetBand": "T3C",
    "targetBandLabel": "Package-native product cockpit (T3C)",
    "implementationMode": "package-native",
    "warnings": [],
    "errors": [],
    "nextMove": "Meal Assistant server-rendered dashboard is inventoried. Planner, calendar, drawer, library, checklist, review, household, and history must migrate to package-native shared components before Tier 3 completion.",
    "externalWorkItems": []
  },
  {
    "project": "hermes-os",
    "name": "Hermes OS",
    "auditStatus": "current",
    "coarseTier": {
      "current": 3,
      "target": 3
    },
    "currentBand": "T3C",
    "currentBandLabel": "Package-native product cockpit (T3C)",
    "targetBand": "T3C",
    "targetBandLabel": "Package-native product cockpit (T3C)",
    "implementationMode": "package-native",
    "warnings": [],
    "errors": [],
    "nextMove": "Hermes OS dashboard hub, operator dashboard artifact, and control-plane artifact are inventoried as planned migration surfaces. The governance project still needs package-native shell/component adoption for its own operator UI.",
    "externalWorkItems": []
  },
  {
    "project": "tlc-capital-group-os",
    "name": "TLC Capital Group OS",
    "auditStatus": "current",
    "coarseTier": {
      "current": 3,
      "target": 3
    },
    "currentBand": "T3C",
    "currentBandLabel": "Package-native product cockpit (T3C)",
    "targetBand": "T3C",
    "targetBandLabel": "Package-native product cockpit (T3C)",
    "implementationMode": "package-native",
    "warnings": [],
    "errors": [],
    "nextMove": "TLC Capital Group OS raw dashboard shell, API route, and dashboard data models are inventoried as planned migration surfaces. The UI must become package-native while keeping the domain data model authoritative.",
    "externalWorkItems": []
  }
];
