// Generated by scripts/sync-dashboard-tier-assessment.mjs from latest-adoption-report.json.
// Do not edit project tier rows manually; rerun npm run dashboard:tier-assessment:sync.

export interface ProjectTierExternalWorkItem {
  ownerProject: string;
  scope: string;
  priority: string;
  action: string;
  reason: string;
}

export interface ProjectTierAssessment {
  project: string;
  name: string;
  auditStatus: "current" | "needs-review" | "stale" | "missing" | "unregistered" | "invalid";
  coarseTier: { current: number | null; target: number | null };
  currentBand: string;
  currentBandLabel: string;
  targetBand: string;
  targetBandLabel: string;
  implementationMode: string;
  warnings: string[];
  errors: string[];
  nextMove: string;
  externalWorkItems: ProjectTierExternalWorkItem[];
}

export interface TierBand {
  band: string;
  tier: 0 | 1 | 2 | 3;
  label: string;
  meaning: string;
}

export const projectTierGeneratedAt = "2026-08-01T23:48:13.661Z";
export const projectTierSourceHash = "f5e3fab4da9eb442891f381c5abb497e932e9af8749c985c753168bf6590795a";

export const tierBands: TierBand[] = [
  {
    "band": "T0P",
    "tier": 0,
    "label": "Planned or governance-only",
    "meaning": "Project is registered for governance/readiness but has no audited operator surface yet."
  },
  {
    "band": "T0L",
    "tier": 0,
    "label": "Raw legacy surface",
    "meaning": "Dashboard exists as a raw report, debug table, prototype, or ungoverned screen."
  },
  {
    "band": "T1A",
    "tier": 1,
    "label": "Adapter-aligned shell",
    "meaning": "Canonical CSS/static adapter is synced, but no surface-level component inventory is enforceable."
  },
  {
    "band": "T1B",
    "tier": 1,
    "label": "Inventoried one-shell report",
    "meaning": "One-shell route and surfaces are inventoried, but the main operator path still reads as a report."
  },
  {
    "band": "T2A",
    "tier": 2,
    "label": "Hybrid shared-component dashboard",
    "meaning": "Primary surface uses shared-kit contracts through a static or hybrid implementation, but is not fully package-native."
  },
  {
    "band": "T2B",
    "tier": 2,
    "label": "Package-native shared-component dashboard",
    "meaning": "Primary surface imports shared components directly and covers required dashboard states, but is not yet a product-grade cockpit."
  },
  {
    "band": "T3A",
    "tier": 3,
    "label": "Cockpit candidate with review gaps",
    "meaning": "Dashboard targets product-grade cockpit behavior but still has Tier 3 visual, shell, chart, proof, or interaction warnings."
  },
  {
    "band": "T3B",
    "tier": 3,
    "label": "Current static/hybrid product cockpit",
    "meaning": "Audited product-grade cockpit is current, but delivery still depends on static or hybrid adapter infrastructure."
  },
  {
    "band": "T3C",
    "tier": 3,
    "label": "Package-native product cockpit",
    "meaning": "Highest maturity: audited Tier 3 cockpit implemented directly with shared package components and complete proof/validation."
  }
];

export const projectTierAssessments: ProjectTierAssessment[] = [
  {
    "project": "khashi-vc",
    "name": "Kashi VC",
    "auditStatus": "needs-review",
    "coarseTier": {
      "current": 3,
      "target": 3
    },
    "currentBand": "T3A",
    "currentBandLabel": "Cockpit candidate with review gaps (T3A)",
    "targetBand": "T3C",
    "targetBandLabel": "Package-native product cockpit (T3C)",
    "implementationMode": "static-adapter",
    "warnings": [
      "packageNative.bridge",
      "tier3.sidebarRailMissing",
      "tier3.commandHeaderMissing",
      "tier3.chartPanelMissing"
    ],
    "errors": [],
    "nextMove": "Repair Tier 3 shell, command-header, chart, overflow, table, and proof evidence in the audited surface.",
    "externalWorkItems": [
      {
        "ownerProject": "khashi-vc",
        "scope": "external-project",
        "priority": "P0",
        "action": "Repair audited Tier 3 surface markers for shell rail, command header, chart panels, semantic chart contracts, and overflow protection.",
        "reason": "A Tier 3 cockpit with review warnings must remain a candidate rather than current."
      },
      {
        "ownerProject": "khashi-vc",
        "scope": "external-project",
        "priority": "P1",
        "action": "Plan package-native dashboard-kit adoption in the owning project.",
        "reason": "Static/hybrid bridges are acceptable current delivery for some projects, but not the highest maturity target."
      }
    ]
  },
  {
    "project": "media-engine",
    "name": "Media Engine",
    "auditStatus": "needs-review",
    "coarseTier": {
      "current": 3,
      "target": 3
    },
    "currentBand": "T3B",
    "currentBandLabel": "Current static/hybrid product cockpit (T3B)",
    "targetBand": "T3C",
    "targetBandLabel": "Package-native product cockpit (T3C)",
    "implementationMode": "static-adapter",
    "warnings": [
      "packageNative.bridge"
    ],
    "errors": [],
    "nextMove": "Preserve the current cockpit while planning the package-native migration in the owning project.",
    "externalWorkItems": [
      {
        "ownerProject": "media-engine",
        "scope": "external-project",
        "priority": "P1",
        "action": "Plan package-native dashboard-kit adoption in the owning project.",
        "reason": "Static/hybrid bridges are acceptable current delivery for some projects, but not the highest maturity target."
      }
    ]
  },
  {
    "project": "media-business-os",
    "name": "Media Business OS",
    "auditStatus": "needs-review",
    "coarseTier": {
      "current": 1,
      "target": 3
    },
    "currentBand": "T1A",
    "currentBandLabel": "Adapter-aligned shell (T1A)",
    "targetBand": "T3C",
    "targetBandLabel": "Package-native product cockpit (T3C)",
    "implementationMode": "static-adapter",
    "warnings": [
      "experienceTier.migrationRequired",
      "packageNative.bridge"
    ],
    "errors": [],
    "nextMove": "Add surface inventory, pick a primary recipe, declare state/data contracts, and make the primary dashboard path enforceable.",
    "externalWorkItems": [
      {
        "ownerProject": "media-business-os",
        "scope": "external-project",
        "priority": "P1",
        "action": "Add `.hermes-dashboard.json` surfaces with required components, markers, owner/reviewer, proof route, and migration note.",
        "reason": "Adapter sync proves CSS availability but not dashboard quality."
      },
      {
        "ownerProject": "media-business-os",
        "scope": "external-project",
        "priority": "P1",
        "action": "Plan package-native dashboard-kit adoption in the owning project.",
        "reason": "Static/hybrid bridges are acceptable current delivery for some projects, but not the highest maturity target."
      }
    ]
  },
  {
    "project": "business-mapper",
    "name": "Business Mapper",
    "auditStatus": "needs-review",
    "coarseTier": {
      "current": 1,
      "target": 2
    },
    "currentBand": "T1A",
    "currentBandLabel": "Adapter-aligned shell (T1A)",
    "targetBand": "T2B",
    "targetBandLabel": "Package-native shared-component dashboard (T2B)",
    "implementationMode": "static-adapter",
    "warnings": [
      "experienceTier.migrationRequired"
    ],
    "errors": [],
    "nextMove": "Add surface inventory, pick a primary recipe, declare state/data contracts, and make the primary dashboard path enforceable.",
    "externalWorkItems": [
      {
        "ownerProject": "business-mapper",
        "scope": "external-project",
        "priority": "P2",
        "action": "Add `.hermes-dashboard.json` surfaces with required components, markers, owner/reviewer, proof route, and migration note.",
        "reason": "Adapter sync proves CSS availability but not dashboard quality."
      },
      {
        "ownerProject": "business-mapper",
        "scope": "external-project",
        "priority": "P2",
        "action": "Plan package-native dashboard-kit adoption in the owning project.",
        "reason": "Static/hybrid bridges are acceptable current delivery for some projects, but not the highest maturity target."
      }
    ]
  },
  {
    "project": "meal-assistant",
    "name": "Meal Assistant",
    "auditStatus": "needs-review",
    "coarseTier": {
      "current": 1,
      "target": 3
    },
    "currentBand": "T1A",
    "currentBandLabel": "Adapter-aligned shell (T1A)",
    "targetBand": "T3C",
    "targetBandLabel": "Package-native product cockpit (T3C)",
    "implementationMode": "server-rendered-legacy",
    "warnings": [
      "experienceTier.migrationRequired",
      "packageNative.bridge",
      "implementationMode.serverRenderedLegacy"
    ],
    "errors": [],
    "nextMove": "Add surface inventory, pick a primary recipe, declare state/data contracts, and make the primary dashboard path enforceable.",
    "externalWorkItems": [
      {
        "ownerProject": "meal-assistant",
        "scope": "external-project",
        "priority": "P1",
        "action": "Add `.hermes-dashboard.json` surfaces with required components, markers, owner/reviewer, proof route, and migration note.",
        "reason": "Adapter sync proves CSS availability but not dashboard quality."
      },
      {
        "ownerProject": "meal-assistant",
        "scope": "external-project",
        "priority": "P1",
        "action": "Plan package-native dashboard-kit adoption in the owning project.",
        "reason": "Static/hybrid bridges are acceptable current delivery for some projects, but not the highest maturity target."
      }
    ]
  },
  {
    "project": "hermes-os",
    "name": "Hermes OS",
    "auditStatus": "needs-review",
    "coarseTier": {
      "current": 0,
      "target": 3
    },
    "currentBand": "T0P",
    "currentBandLabel": "Planned or governance-only (T0P)",
    "targetBand": "T3C",
    "targetBandLabel": "Package-native product cockpit (T3C)",
    "implementationMode": "planned",
    "warnings": [
      "experienceTier.migrationRequired",
      "packageNative.bridge"
    ],
    "errors": [],
    "nextMove": "Decide whether this project owns an operator dashboard; if yes, add surface inventory and package-native cockpit scaffolding.",
    "externalWorkItems": [
      {
        "ownerProject": "hermes-os",
        "scope": "external-project",
        "priority": "P1",
        "action": "Create or confirm the production dashboard surface inventory in the owning project.",
        "reason": "Central registry can track planned readiness, but implementation surfaces must live in the owning project."
      },
      {
        "ownerProject": "hermes-os",
        "scope": "external-project",
        "priority": "P1",
        "action": "Plan package-native dashboard-kit adoption in the owning project.",
        "reason": "Static/hybrid bridges are acceptable current delivery for some projects, but not the highest maturity target."
      }
    ]
  },
  {
    "project": "tlc-capital-group-os",
    "name": "TLC Capital Group OS",
    "auditStatus": "needs-review",
    "coarseTier": {
      "current": 0,
      "target": 3
    },
    "currentBand": "T0P",
    "currentBandLabel": "Planned or governance-only (T0P)",
    "targetBand": "T3C",
    "targetBandLabel": "Package-native product cockpit (T3C)",
    "implementationMode": "planned",
    "warnings": [
      "experienceTier.migrationRequired",
      "packageNative.bridge"
    ],
    "errors": [],
    "nextMove": "Decide whether this project owns an operator dashboard; if yes, add surface inventory and package-native cockpit scaffolding.",
    "externalWorkItems": [
      {
        "ownerProject": "tlc-capital-group-os",
        "scope": "external-project",
        "priority": "P1",
        "action": "Create or confirm the production dashboard surface inventory in the owning project.",
        "reason": "Central registry can track planned readiness, but implementation surfaces must live in the owning project."
      },
      {
        "ownerProject": "tlc-capital-group-os",
        "scope": "external-project",
        "priority": "P1",
        "action": "Plan package-native dashboard-kit adoption in the owning project.",
        "reason": "Static/hybrid bridges are acceptable current delivery for some projects, but not the highest maturity target."
      }
    ]
  }
];
